### ISSUE TITLE
Adding "No internet connection" message 

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#10]
**Is your feature request related to a problem? Please describe.**
Adding a "No internet connection" message or warning would be a good improvement.
- The loader is visible indefinitely if the user searches for something and there is no internet connection. They might not know that they are not connected to the internet.
- When viewing the bookmarks, the thumbnails and the metadata is fetched from the API. Some users might feel that all this data is saved to the extension and they don't need the internet to access them. Therefore, showing the "No internet connection" message can help. 

**Describe the solution you'd like**
The extension uses snack bar for passing messages to the user, but they disappear after 1 second and also they are very small in size. Therefore, using something that would be there until the user connects to the internet would be good, like a popup.

**Describe alternatives you've considered**
We can discuss any other effective way of showing the message.

**Comment by jeffreymeng** [comment]
Hi! I can work on this.

**Comment by makkoncept** [comment]
Sure, go ahead!

**Comment by Lawrence4code** [comment]
I'd like to work on this, please.

**Comment by makkoncept** [comment]
Sure, go ahead!

**Comment by jeffreymeng** [comment]
Ok. I was having some trouble getting the development version of the extension to launch without errors, and that's why it was taking longer than expected, but I'm totally fine with somebody else working on this.

**Comment by makkoncept** [comment]
@jeffreymeng If you are still facing some problems spinning up the local environment, you can create an issue for that and we can together figure things out.
Also, if you think that you can add something to the documentation about setting up the extension, feel free to create an issue and submit a PR for it.
Thanks

**Comment by codingonHP** [comment]
@jeffreymeng Are you still having trouble setting up the dev env?
You can post your errors here and we can help you sort it out

**Comment by jeffreymeng** [comment]
Oh, I'll just give @Lawrence4code the opportunity to work on this.

**Comment by sharmaaditya570191** [comment]
Hi @makkoncept . I would like to take this up. Please suggest where to place `No internet connection` message.

**Comment by sharmaaditya570191** [comment]
Can I take this up @makkoncept ?

**Comment by makkoncept** [comment]
@sharmaaditya570191 go ahead!
