### ISSUE TITLE
Load more button is still present when no images are found

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#100]
**Describe the bug**
When there are no images in a search query, the load more button is still rendered. Even though clicking it would not do fill the grid with empty thumbnails or show the loading animation forever, but nonetheless it should not be present in this particular case.

**To Reproduce**
1. Go to Extension
2. Search for random gibrish charachters ('eiejndinec' -> tried and tested)
3. See error

**Expected behavior**
The load more button should not be present when no images are found.

**Screenshots**
![Screenshot (252)](https://user-images.githubusercontent.com/34679965/73133546-25905a00-4050-11ea-81c7-b968498d264f.png)

**Comment by gauravahlawat81** [comment]
Hey ,I would like to take up this issue. Can I get assigned to this ?

**Comment by gauravahlawat81** [comment]
Hey, I have fixed this issue
