### ISSUE TITLE
"Select all" button freezes in the bookmarks section

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#102]
**Describe the bug**
The following course of action freezes the select all button in the bookmarks section (checkout the gif below)
click on the _select all_ button so the images are selected --> press the _home_ icon to go to the search section  --> go back to the bookmarks section --> press the _select all_ button again.

**To Reproduce**
1. Bookmark some images
2. follow the steps described above.

**Expected behavior**
The click on the button should toggle between selecting all the images and deselecting all the images.

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34679965/73184278-328d7600-4142-11ea-932b-64bd318a7038.gif)

**Comment by AmanR28** [comment]
@makkoncept  Can I fix it, please?

**Comment by makkoncept** [comment]
@AmanR28 Can you please solve the issue assigned to you first (#79). This is to avoid confusion and letting others get a chance to contribute to the project. If it remains unassigned after we have solved the issue, you can take it up.

**Comment by AmanR28** [comment]
@makkoncept I felt that it was fault in my code, and I know how to fix it (Code is ready), so I should fix it.

**Comment by makkoncept** [comment]
Okay, Submit the PR when you are ready.
