### ISSUE TITLE
Unable to fetch the query given by the user 

### ISSUE THREAD

**Issue by aryamanpuri** [creativecommons/ccsearch-browser-extension#104]
Browser: Google Chrome
@makkoncept 

![Screenshot from 2020-01-28 22-19-39](https://user-images.githubusercontent.com/43513114/73285833-a4d28900-421c-11ea-9a61-3c1998ebabba.png)
It does not give any result on doing a search , just loading

**Comment by makkoncept** [comment]
This notification is triggered when the extension is not able to fetch the Provider list from the API and backup provider list is used. Maybe the internet was not connected when you were searching. Can you confirm that this was not the case. BTW, is this extension from the google store or you have build it locally?

**Comment by aryamanpuri** [comment]
@makkoncept Internet is working properly, and I have built it locally.

**Comment by makkoncept** [comment]
I have just cloned the repository and build it. It is working for me. Can you open the following url in your browser? (https://api.creativecommons.engineering/image/search?q=hello)

**Comment by aryamanpuri** [comment]
@makkoncept Okay I got it, the link is blocked here, so the problem lies in my side.

**Comment by makkoncept** [comment]
Yeah, maybe a VPN can help.
