### ISSUE TITLE
Some creator links are opening the extension in the new tab

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#106]
**Describe the bug**
When we click on the creator link in the information popup, it opens the creator profile on a website (like flickr ) in a new tab. But some creator links instead opens the extension in a browser tab. 
In the API response, not every image has a creator url associated with it. For those instances, the creator url is set to "#". Instead, the creator name should be rendered as plain text and not a url.

**To Reproduce**
1. Search for "hello"
2. Click on the very first image.
3. In the info tab, click on the creator name.

**Expected behavior**
Those images which do not have the creator link should render the creator name as plain text.

**Screenshots**

![ezgif com-crop](https://user-images.githubusercontent.com/34679965/73337164-c887e480-4299-11ea-85f3-c870b09fac8b.gif)

**Comment by gauravahlawat81** [comment]
Can I take up this issue ?

**Comment by gauravahlawat81** [comment]
Also how can I search for good issues by myself ? I don't want to keep solving the easy ones :(

**Comment by makkoncept** [comment]
@gauravahlawat81 sure, go ahead. 
The focus now is in pseudo rolling release of the extension. Each release fixes a couple of bugs and sometimes add atleast one feature. I am sure that as soon as we are done with the issues related to the release of `v1.2.6`, new batch of interesting issues will be there for you to work on. You can, of course, look at the current unassigned open issues.
