### ISSUE TITLE
Let the user know that "backup" filters have been loaded

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#11]
**Is your feature request related to a problem? Please describe.**
The CC Catalog API adds (and sometimes removes) the image providers available. Therefore, the extension loads the latest providers using the [/statistics/image](https://api.creativecommons.engineering//statistics/image) endpoint of the API at the start of the popup session (same for the "Filters" tab in the options page).
If there is no internet connection or the API is giving some error, extension loads from a "backup" list of providers. I think that letting the user know that the "backup" filters have been loaded for the current session would be good.

**Describe the solution you'd like**
We can use snack bar for showing the message but increasing the time duration from ~1sec to something more significant is needed.

**Comment by codingonHP** [comment]
Can I pick this up?

**Comment by makkoncept** [comment]
Sure, go ahead!
