### ISSUE TITLE
Search section does not reset when after an invalid search query

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#124]
**Describe the bug**
When the user enters a search query, the previous image thumbnails are removed from the grid. If the new query is invalid, then there are not any images to fill the grid as the API response returns a validation error. Though the user is notified that the query is invalid, the image grid is of the same size. Refer the gif below.

**To Reproduce**
1. Search for something
2. Load a couple more images.
3. Prepend ';' to the search query (this is an invalid query)

**Expected behavior**
The search section should reset to the default state.

**GIF**
![ezgif com-crop](https://user-images.githubusercontent.com/34679965/73649441-cbbe0e80-46a5-11ea-90f4-3aea42648c80.gif)

**Comment by DantrazTrev** [comment]
I've resolved the issues in the PR can i take up this issue

**Comment by makkoncept** [comment]
@DantrazTrev I have reviewed the PR and added some comments. You can work on a different issue after the PR is finally merged.

**Comment by cristomathew** [comment]
Is it still available? Can I take it up.

**Comment by makkoncept** [comment]
@cristomathew Sure, go ahead!
