### ISSUE TITLE
Add a section about how to debug the extension during development in the readme.

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#126]
**Is your feature request related to a problem? Please describe.**
Unlike in chrome and opera, debugging in firefox is not very intuitive. Also, if you are a beginner, even chrome and opera can cause some problems.
 
**Describe the solution you'd like**
Add a section in the README of how to debug the extension on chrome, opera and firefox. You can checkout https://github.com/creativecommons/ccsearch-browser-extension/pull/110#issuecomment-580333051. It is not the best example as you can significantly improve it. 
- _Image speaks louder than words_. Make sure to add good screenshots. You can edit them to highlight or mark something.
- It should be precise yet informative.

**Comment by jsbentley34** [comment]
All for one one for all

**Comment by techievivek** [comment]
@makkoncept If no one is working on this, can I take this one?
Thank you

**Comment by makkoncept** [comment]
@techievivek go ahead!

**Comment by techievivek** [comment]
@makkoncept  Do I have to create a new heading under Installation for debugging instruction or I should add in Installation heading itself?
I have tested for all the 3 browsers. (Opera and Chrome have same debugging style.)

**Comment by makkoncept** [comment]
@techievivek I have added some review comments your PR. Please take a look.
