### ISSUE TITLE
Change the snackbar message when the backup providers are loaded

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#129]
When the extension does not get the provider list from the API, it uses the backup providers (hard-coded provider list) so that the provider filter dropbox is not empty. 
The user is notified about this in a snackbar message. 

![Screenshot from 2020-02-06 23-01-10](https://user-images.githubusercontent.com/34679965/73962830-2a4cec00-4935-11ea-9745-78747eba9a2c.png)

Change the snackbar message to `Unable to fetch providers. Using backup providers.`

**To View the snackbar message**
1. Open the extension after turning your internet off
2. See snackbar message

**Comment by alti21** [comment]
Hi, can I work on this issue?

**Comment by makkoncept** [comment]
@alti21 sure, go ahead.

**Comment by alti21** [comment]
Hi @makkoncept when I run npm run dev I am getting an error: 'rm' is not recognized as an internal or external command, operable program or batch file.
This comes from the script: "clean": "rm -rf './dist'"

**Comment by makkoncept** [comment]
@alti21 You must be running the command on windows command prompt, which does not support UNIX commands. You can use [git bash](https://gitforwindows.org/)(which support some basic UNIX commands) or Windows subsytem for linux [[WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10)] (which is basically linux kernel running in harmony with the windows OS).

**Comment by DantrazTrev** [comment]
Hi @alti21 is this issue still open and are you still working on it

**Comment by alti21** [comment]
Hi, actually I will pass on this issue for now
