### ISSUE TITLE
Use Font Awesome icons for better compatibility with Vocabulary

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/ccsearch-browser-extension#13]
The extension uses icons from Material Design by Google. This is evidenced here:
![image](https://user-images.githubusercontent.com/16580576/64247146-de33f080-cf2b-11e9-8017-b3c810997eac.png)

But Vocabulary has been designed with Font Awesome and even comes with some Font Awesome icons pre-packaged into the bundle. So for consistency with the rest of CC applications, Material icons should be replaced with their Font Awesome counterparts.

Font Awesome has replaced icons from The Noun Project in CC Search as well with creativecommons/cccatalog-frontend#413.

**Comment by efl7a** [comment]
I would like to work on this.
