### ISSUE TITLE
Improve the select/deselect mechanism of the button in bookmarks section

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#131]
**Present Behaviour**
- In the bookmarks section, on clicking the "Select all" button, all the bookmarks are selected and the button now reads "Deselect all". But, as soon as the user manually deselect a single bookmark, the button changes back to "Select all". 
- If the user goes to the bookmarks section and manually select some images. The button does not change to "Deselect all" until and unless all the images are selected.

**Expected Behaviour**
- The button should not change to "Select all", until all the images have been deselected.
- The button should change to "Deselect all" as soon as the user has selected even one image.

The above improvements are more intuitive for the user.
![ezgif com-crop](https://user-images.githubusercontent.com/34679965/74148560-ba3bb000-4c2b-11ea-8e7f-e0454708aa91.gif)

**Comment by DantrazTrev** [comment]
Can I take up this issue?
