### ISSUE TITLE
Remove the redundant stylesheet rules in _grid.scss

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#132]
There are some rules defined in [_grid.scss](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/sass/layout/_grid.scss) that are not used in the extension at all (eg: `.col-1-of-3`, `.col-2-of-3`. In addition to that, a few redundant properties are also present. Remove them. Make sure that you do not break anything.

**Comment by thescriptninja** [comment]
Hi! Can I work on this?

**Comment by makkoncept** [comment]
@thescriptninja sure, go ahead.

**Comment by cristomathew** [comment]
@thescriptninja are you still working on this

**Comment by thescriptninja** [comment]
@cristomathew I unable to find more redundancies than I did in #145 . Not currently working on it.

**Comment by harsh551** [comment]
Is anyone working on this issue ??

**Comment by cristomathew** [comment]
So if possible can i check it out.

**Comment by makkoncept** [comment]
@harsh551 I have assigned you an issue. @cristomathew go ahead with this one

**Comment by cristomathew** [comment]
Hi it seems everything is fine in grid.scss and nothing much to edit.

**Comment by makkoncept** [comment]
No problem! Closing this.
