### ISSUE TITLE
Improve the UI of "Clean Search" button

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#134]
**Is your feature request related to a problem? Please describe.**
The "Clear Search" button becomes visible when the user search for something. By clicking it, the search results are removed from the local Storage and image grid. 

**Present UI**
- a small cross enclosed inside a red square.
- Both the color and the position is odd.

![74013862-66269680-49b3-11ea-99e6-cec6ae68fbb1](https://user-images.githubusercontent.com/34679965/74274631-68348080-4d38-11ea-8817-90303a7836d2.gif)

**Describe the solution you'd like**
This one is tricky. We have a very limited space available. 
- The first thought is to add an icon alongside the filter icon when there are images in the grid. But, most users would assume it to be the icon that will clear the text they have written in the search box.
- A better solution can be to add a button of absolute position in bottom left (?)

Better ideas are welcomed.

**Comment by AmanR28** [comment]
Can i claim this issue ??

**Comment by makkoncept** [comment]
@AmanR28 Go ahead

**Comment by makkoncept** [comment]
@AmanR28 Please make the PR soon, as v1.2.7 gotta be released in a couple of days and this issue is  the bottleneck.

**Comment by AmanR28** [comment]
![Contols_-_Add_On-35-512](https://user-images.githubusercontent.com/54908728/74449191-38a18780-4ea2-11ea-9bd9-c7676ae05aaf.png)

@makkoncept Is this UI of close button alright!

Should I keep the position the same as it is, as other putting the button at bottom line will make user wander what it is?
As the users know that a cross inside the input box clears the search, perhaps the one that is out will clear all.
Positioning at the bottom will make the user wander what it is?

**Comment by makkoncept** [comment]
@AmanR28 The icon is fine. 
The position that you are recommending might not look good in my opinion but it can be a good starting point for the implementation in the PR.
