### ISSUE TITLE
Remove unused variables from base.js

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#136]
Most of the variables in the code are defined inside `elements` object in `base.js`. Check that all of them are being used somewhere outside `base.js` and if not, remove them. (for eg: `getBookmarks` is redundant). 
You can complete this task easily by using the search feature of any modern editor.

**Comment by DantrazTrev** [comment]
Can I take up this one?

**Comment by makkoncept** [comment]
@DantrazTrev Let's first merge your pending PR. I have added a review comment on it.

**Comment by keshav2212** [comment]
Hi @makkoncept, Can I work on this issue ?

**Comment by makkoncept** [comment]
@keshav2212 Sure, go ahead.

**Comment by keshav2212** [comment]
@makkoncept Thanks, I have sent the PR for it.
