### ISSUE TITLE
Set up landing page for the browser extension.

### ISSUE THREAD

**Issue by kgodey** [creativecommons/ccsearch-browser-extension#143]
Some feedback we got on Twitter about sending people to the blog post for information about the browser extension:

> I installed, but there are way too many clicks and too much text. I clicked `CC Search Browser Extension`. That takes me to GitHub where I can find the links to install on Firefox | Chrome | Opera if I look hard enough. Want to increase the number of installs? Send people to a page with big buttons that link directly to the installs for Firefox/Chrome/Opera. This is really easy to use. 99% of people don't need/want to read the help/background, but you could link to the help within the UI.

I think it would be good to create a simple static landing page using Vocabulary and hosted on GitHub Pages that just provided easy links to install the extension + a bit of background. We can use this as a homepage for the extension.

@makkoncept, I'm assigning to you to flesh it out further and make this issue ready for contribution. Let me know if you have questions.

**Comment by techievivek** [comment]
@makkoncept @kgodey I have no pending PR and I am interested to work on this as I will get my hands on the `Vocabulary design system`. Also, I understand the essence of this as not everyone is a developer so this will make everyone feel home.
First, we can work on the designs and images and then once it is ready I will start developing.
For inspiration: https://www.grammarly.com/
**Suggestion**
We can have a link to this landing page from [CC search website](https://ccsearch.creativecommons.org/) as the extension is easily accessible and feature-packed.

**Comment by makkoncept** [comment]
@techievivek thanks for showing interest in this issue. Can you please elaborate on what are you planning to build the site on? and how will you go about integrating vocabulary with it?

**Comment by techievivek** [comment]
@makkoncept I am planning to style the site using vocabulary CSS along with some custom CSS, if required.
It will be pure HTML+ vocabulary CSS and JS.
It will be a single page static website with some good images/gif, buttons and little text content.

**Comment by techievivek** [comment]
I won't be using the Vue version.

**Comment by techievivek** [comment]
@makkoncept I have no prior experience with Vocabulary so tomorrow I will set up everything, play with it for some time and will update you on how exactly I will be proceeding with it and discuss things that I am not clear about.

**Comment by makkoncept** [comment]
@techievivek One major problem will occur when using vocabulary CSS. Some of the major components of the vocabulary have dynamic nature which can not be achieved only by CSS and then to make them work we have to write custom JavaScript (which could lead to errors or inconsistencies).

I am not saying that writing custom JavaScript to make the components work is the worst thing in the world but since we have a clean canvas here, the best way, in my opinion, is to use Vue.

**Comment by kgodey** [comment]
@makkoncept we're rewriting Vocabulary, the components you're referring to will no longer be available. We'll be mostly using it via CSS and we'll only have a minimal subset of components in Vue. Many of the changes have already been made.

**Comment by makkoncept** [comment]
Oh, nice to hear this! I was not up to date with the development of vocabulary. So, when will be the documentation or a starting guide be made available?

**Comment by kgodey** [comment]
Documentation is at https://cc-vocabulary.netlify.com/ and https://cc-vue-vocabulary.netlify.com/ (currently empty) and is being updated regularly.

We don't have a getting started guide yet. It would be great if you could look at the current documentation and let us know what questions you have, it will help us figure out what documentation we need to write next.

**Comment by makkoncept** [comment]
Okay, great :+1:

**Comment by makkoncept** [comment]
@techievivek I am assigning this to you. If you face any problems, do let us know. I will be also learning with you :)

**Comment by techievivek** [comment]
@makkoncept Can we discuss on what and all things should we include in the page. And what will be the flow of information from top to bottom of the page?
Also, I am thinking of giving **sectional links** in the navbar, to navigate to different sections of the page.
Please guide me through this.

**Comment by makkoncept** [comment]
You can refer to these blog posts to decide about the content to put on the site https://opensource.creativecommons.org/blog/entries/introducing-cc-search-extension/ and https://creativecommons.org/2020/01/06/cc-search-browser-extension/ . As mentioned in the issue description, we need a page that gives a general introducation about the extension and it's features and have browser addon store links.

The following are some points. But, you can skip some of them if you think that your design would not need it.

- We can add lots of images. For now, you can use placeholders.
- For each image, we can have an associated feature. Each feature will have a heading and then a brief description. 

- The links to the browser extension stores are a must. We need to emphasize them and make sure that people don't have a hard time finding them on the page.

-  We have to adopt a design that will make it easy to add/remove the listed features. Meaning, that we have to avoid a design where we put a single feature in each section. Then, the user has to scroll a lot to reach the end.

- You can go through the landing pages of the top submissions on [producthunt](https://producthunt.com) for inspiration.

**Comment by techievivek** [comment]
> You can refer to these blog posts to decide about the content to put on the site https://opensource.creativecommons.org/blog/entries/introducing-cc-search-extension/ and https://creativecommons.org/2020/01/06/cc-search-browser-extension/ . As mentioned in the issue description, we need a page that gives a general introducation about the extension and it's features and have browser addon store links.
> 
> The following are some points. But, you can skip some of them if you think that your design would not need it.
> 
>     * We can add lots of images. For now, you can use placeholders.
> 
>     * For each image, we can have an associated feature. Each feature will have a heading and then a brief description.
> 
>     * The links to the browser extension stores are a must. We need to emphasize them and make sure that people don't have a hard time finding them on the page.
> 
>     * We have to adopt a design that will make it easy to add/remove the listed features. Meaning, that we have to avoid a design where we put a single feature in each section. Then, the user has to scroll a lot to reach the end.
> 
>     * You can go through the landing pages of the top submissions on [producthunt](https://producthunt.com) for inspiration.

Thank you for the help, I will go through all the links provided and keep you will update about every step. I am also planning to first create a wireframe and share it with you for the feedback.

**Comment by techievivek** [comment]
@makkoncept I have made my very first design, can you please help me in which **feature design** should I go with and also provide feedback for the rest.
Here is the link: https://www.figma.com/file/7N1ZEZ6vZwrFq01Xs0cqZv/Untitled?node-id=0%3A1

**Comment by techievivek** [comment]
@makkoncept Very first image will be a gif one showcasing very feature and usage.

**Comment by makkoncept** [comment]
The Figma link is giving 404

**Comment by techievivek** [comment]
> The Figma link is giving 404

I am able to access the content from the above link.
I am also attaching a screenshot for the design.
![Screenshot_20200321-200010](https://user-images.githubusercontent.com/35863227/77228667-dd546a80-6bae-11ea-810b-64a46fc5ebe7.jpg)

**Comment by techievivek** [comment]
@makkoncept I have doubt regarding how to show features? GitHub link in the top will be similar to as of CC open source website. First image will be a gif one and then some important features can be shown.

**Comment by makkoncept** [comment]
Maybe you have not made the file public

![Screenshot from 2020-03-21 21-09-30](https://user-images.githubusercontent.com/34679965/77230176-586e4e80-6bb8-11ea-8946-678b36f7b514.png)

**Comment by techievivek** [comment]
> Maybe you have not made the file public
> 
> ![Screenshot from 2020-03-21 21-09-30](https://user-images.githubusercontent.com/34679965/77230176-586e4e80-6bb8-11ea-8946-678b36f7b514.png)

This is the design that I have made, can you give review on it.
![Screenshot_20200321-200010](https://user-images.githubusercontent.com/35863227/77250853-a47cca00-6c70-11ea-979b-9609759b5cbd.jpg)

**Comment by techievivek** [comment]
@makkoncept Yes there was some permission issue, I have changed it now. Please have a look.

**Comment by makkoncept** [comment]
For the start, the design looks good. I have a few points:
- Make sure to integrate vocabulary into the site because most of the components would look better that way. For eg, in the design above, the [header](https://cc-vocabulary.netlify.com/?path=/story/patterns-header--big), [buttons](https://cc-vocabulary.netlify.com/?path=/story/elements-buttons--button-primary), [footer](https://cc-vocabulary.netlify.com/?path=/story/patterns-footer--main) components of vocabulary would look much better. Also, using the vocabulary [color-pallete](https://cc-vocabulary.netlify.com/?path=/docs/tokens-color--figma) and [spacing](https://cc-vocabulary.netlify.com/?path=/docs/tokens-spacing--figma) would be good for keeping things consistent.
- Since there is no grid support in the vocabulary like the older version, it would be better that you use [CSS grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) for that instead of any third-party dependency.
- As far as the design of the features section is concerned, the second design would not let us specify all of the features and the first design does not have space for the text content. I would propose that we use the second design which we can use to highlight the top 3-4 features of the extension and then at the end, we can use a table to list other features. Since the [table component](https://cc-vocabulary.netlify.com/?path=/docs/layouts-table--basic-content) is already supported by the vocabulary, this would be very easy to implement.

**Comment by techievivek** [comment]
@makkoncept Yes I will be using the Vocabulary design system as you can see from the above image, buttons in the Vocabulary design system are far better as of the above design. And yes I will be using pure CSS without any dependency. And we can go with 2nd feature design and tabular.
For the feature part, I am planning to show these features on top.
1. Search and filter CC Licensed content
2. One-Click download with easy attribution
3. Bookmark Image
4. Dark Mode
Please share your views regarding this.

**Comment by makkoncept** [comment]
Yeah, these features seem fine to start with.

**Comment by techievivek** [comment]
@makkoncept Just one more doubt before I start coding, should I create a new directory, so that we use Github pages for this directory.

**Comment by makkoncept** [comment]
Yes, that's the plan.

**Comment by techievivek** [comment]
@makkoncept  @kgodey  Please have a look at my initial attempt http://techievivek.com/cc/ , also provide me with proper feedback and little help( as it is really difficult to incorporate what is in storybook and what is being used in this design).
I need a little help with footer and logo, I am unable to get the same result as shown in storybook in my deigns like for [footer](https://cc-vocabulary.netlify.com/?path=/docs/patterns-footer--main)
I am not getting how can I can include logo, license badges in this design.
(Also I have hosted the files on my site as I was facing some issue with codepen).

**Comment by techievivek** [comment]
@makkoncept Also I have made two design for other features, please help me with which one we can go with further improvements.

**Comment by makkoncept** [comment]
@techievivek The initial design looks good. There is a lot of room for improvement though. I will get back to you after testing and experimenting with the PR.

**Comment by techievivek** [comment]
@makkoncept Yes we can improve a lot. Also it was really messy incorporating Vocabulary, so please have a look.
Thank you

**Comment by techievivek** [comment]
@makkoncept We can also use slide-in CSS animation for each features when it comes in focus?

**Comment by makkoncept** [comment]
@techievivek yes we can. I am sorry, I am not able to take out time for the PR. I will try to look into soon.

**Comment by techievivek** [comment]
> @techievivek yes we can. I am sorry, I am not able to take out time for the PR at the moment. I will try to look into it soon.

No issue, please take your time.
