### ISSUE TITLE
API v1: Update the getProviderUrl in fetchProviders()

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#146]
The extension loads the latest image sources from the catalog API every time it starts. The sources are loaded  at two places (filter dropdown and  options page). Both of these uses [fetchProviders() function in utils](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/utils.js#L59). 

- Update the api url from https://api.creativecommons.engineering/statistics/image to https://api.creativecommons.engineering/v1/sources
- Since the new api version uses `sources` to refer to image providers, change the variable `getProviderUrl` to `getSourcesUrl` and `fetchProviders()` to `fetchSources()`. 
    - Make sure to also make the necessary wherever the `fetchProviders()` function was used in the code.

**Comment by vrameshj** [comment]
Hi, I'd like to take up this issue.

**Comment by makkoncept** [comment]
@vrameshj Let's work on a single issue at a time. I have assigned you another issue on which you commented.

**Comment by CodeMonk263** [comment]
Can i work on this issue

**Comment by makkoncept** [comment]
@CodeMonk263 go ahead

**Comment by cristomathew** [comment]
@CodeMonk263 are you still working on this
