### ISSUE TITLE
API v1: Update getRequestUrl in SearchModule.js and SearchModule.test.js

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#147]
The [getRequestUrl() in SearchModule.js](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/searchModule.js#L35) returns the API URL with the necessary query parameters that must be used to search for the images. 
- Change the API endpoint from https://api.creativecommons.engineering/image/search to https://api.creativecommons.engineering/v1/images
- Since the new API has also changed the query parameters, update:
    - `li` to `license`.
    - `lt` to `license_type`
    - `pagesize` to `page_size`
    - `provider` to `source`
- Also, change the instances of `userSelectedProvidersList` to `userSelectedSourcesList` wherever the data Structure is defined and passed to the functions.

**Update tests**
 The above changes are bound to break some tests in `SearchModule.test.js`. Fix those also.

**Comment by Arunhari333** [comment]
I would like to work on this issue
