### ISSUE TITLE
API v1: update the sample image detail response in infoPopupModule test

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#148]
In [InfoPopupModule.test.js](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/tests/infoPopupModule.test.js), `getHtmlAttribution` and `getPlainAttribution` functions are tested. For that, we have a sample image detail response object defined. 

Update the response object according to the new version of the API. Use the same image id(`bafff537-0c74-4fa6-9867-401e440e97f5`) so that we don't have to change the tests. 

In simpler words, update the current response object with the [new one](https://api.creativecommons.engineering/v1/images/bafff537-0c74-4fa6-9867-401e440e97f5).

**Comment by vrameshj** [comment]
Hi, would like to take this up.

**Comment by makkoncept** [comment]
@vrameshj Sure, go ahead!
