### ISSUE TITLE
API v1: update getImageData() and LoadImages()

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#149]
[getImageData(id) in infoPopupModule.js](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/infoPopupModule.js#L163) and [loadImages() in bookmarkModule.js](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/bookmarkModule.js#L82) uses the image search endpoint of the cc catalog API ([old docs](https://api.creativecommons.engineering/v0/#operation/image_detail) and [new doc](https://api.creativecommons.engineering/v1/#operation/image_detail)). Update and mould the implementation of these function in accordance of the new API version.
- change the url from http://api.creativecommons.engineering/image/{id} to https://api.creativecommons.engineering/v1/images/{id}
- Since `provider_code` key is removed in the new version, use `source` in loadImages().
- Since `provider` key is removed in the new version, use `source` in getImageData().
- Also, change the instances of `provider` variable to `source` in these functions.

**Comment by Arunhari333** [comment]
I would like to work on this issue

**Comment by makkoncept** [comment]
@Arunhari333 Thanks for showing the interest to contribute to this project! Let's work on a single issue at a time. You already have submitted a PR for a different issue.

**Comment by makkoncept** [comment]
@Arunhari333 You can take this up. Please confirm by commenting if you start working on this.

**Comment by Arunhari333** [comment]
@makkoncept Yes, I am still interested

**Comment by Arunhari333** [comment]
Should only provider_code in loadImages() and provider in getImageData() be changed? Or should provider be changed to source in other places like popupProvider, css classes etc?

**Comment by makkoncept** [comment]
@Arunhari333 Just stick to the code that is logically connected to the function `loadImages()` and `getImageData()`. For example the variable [providerImageElement](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/bookmarkModule.js#L126) needs to be changed to `sourceImageElement` but changing something not connected (for eg [providerAPIQueryStrings](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/popup.js#L44) object name)) is not needed.

**Comment by Arunhari333** [comment]
Ok done, but before I commit, there is a variable [provider](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/bookmarkModule.js#L104) used in `bookmarkModule.js`. Since `provider_case` was renamed to `source`, provider cannot be given the same name, so I did not change it, is that ok?

**Comment by makkoncept** [comment]
I think that you can change variable name of [provider](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/bookmarkModule.js#L104) to `source` as being a local variable to the function `loadImages` it won't create a problem?

**Comment by Arunhari333** [comment]
Right.

**Comment by Arunhari333** [comment]
Ok. Done.
