### ISSUE TITLE
"Fetching Providers List..." message is not visible in darkmode

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#15]
**Describe the bug**
Since the color of the message is black and it does not change in the dark mode, the message is not visible.
See the screenshot below.

**To Reproduce**
1. Set the dark mode as default.
2. After opening the extension, immediately open the filters section. (_be quick!_)

**Expected behavior**
The message color should change to something bright (preferably white) in dark mode.

**Screenshots**
![Screenshot (200)](https://user-images.githubusercontent.com/34679965/65821866-20b1ca00-e259-11e9-8d47-f648a7020fb8.png)

**Desktop**
 - OS: Windows
 - Browser: chrome
 - Version:1.0.0

**Additional context**
This can easily be solved by adding a new rule in `src/popup/sass/components/_darkmode.scss` for `section-filter__provider-loading-mes`.
Make sure to nest it inside `body.dark` rule.

**Comment by ritesh-pandey** [comment]
@makkoncept Can I take this up?

**Comment by makkoncept** [comment]
@ritesh-pandey Go ahead!
