### ISSUE TITLE
API v1: make host permissions more explicit for the new API version

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#150]
In the chrome and opera manifest files, update the wildcard entry of the catalog API from https://api.creativecommons.engineering/* to https://api.creativecommons.engineering/v1/*.

**Comment by makkoncept** [comment]
Blocked for now.

**Comment by Blackcipher101** [comment]
@makkoncept can I start working on this issue

**Comment by makkoncept** [comment]
@Blackcipher101 According to the updated [Contribution guidelines](https://opensource.creativecommons.org/contributing-code/) linked in the projects [CONTRIBUTING.md](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/CONTRIBUTING.md), you don't have to ask for permission to work on an issue marked as `good first issue`. After making sure that no one is working on it, just comment on the issue that you are working on it.
