### ISSUE TITLE
Confirm with user if they want to clear the search.

### ISSUE THREAD

**Issue by techievivek** [creativecommons/ccsearch-browser-extension#157]
**Is your feature request related to a problem? Please describe.**
![clear btn](https://user-images.githubusercontent.com/35863227/75099213-0a7c2000-55e5-11ea-85ef-8822d61fddfd.png)
At times when user wants to click on the **filter button**, by mistake, they click on the **clear button** as they are closeby and there is no defined boundary/border visible between them, so there must be an extra option in settings where user can check/tick if they need to be asked for confirmation every time clear button gets clicked(knowingly or unknowingly).

**Describe the solution you'd like**
If the user has unchecked this particular settings option, we can directly clear the input field and related results, but if he has checked this settings option then every time we will ask for confirmation to clear the fields. If confirmed by the user we can clear both result and the input field else we will do nothing.
This may save time and data usage of users.

**Describe alternatives you've considered**
To go with the present functionality.

**Additional context**
I am keeping it as a **settings option** so that user don't get bothered by this activity of asking confirmation every time.

**Comment by makkoncept** [comment]
@techievivek Nice idea! 

This can be broken down into two things:
- Ask for confirmation in a popup if the user wants to indeed clear the search results.
- Add a checkbox on the options page to toggle this feature.

This issue will focus on the first objective. 

**Confirmation popup box implementation**

Taking from the conversation in https://github.com/creativecommons/ccsearch-browser-extension/pull/82
- Do not use any external dependency for this.
- Do not use the DOM `confirm()` method, as it does not match with the design.
- Make sure to make the utility modular and reusable (eg: like the showNotification() utility)
- Make and use `src/popup/sass/components/_confirm_popup.scss` as the stylesheet for the component.

**Comment by techievivek** [comment]
@makkoncept yeah exactly what you have explained. So do I have to add another issue too?

**Comment by makkoncept** [comment]
Let me make the issue. If you want to work on this, comment below after we have merged your pending PR.

**Comment by techievivek** [comment]
@makkoncept Please have a look I have added the updated image for inspecting in chrome.

**Comment by techievivek** [comment]
@makkoncept Yes I would like to work on this one.

**Comment by techievivek** [comment]
@makkoncept You can assign me this one now.
Thank you.

**Comment by techievivek** [comment]
@makkoncept I will make this modular, please go through it and let me know what else I can improve.

**Comment by makkoncept** [comment]
@techievivek You can start by removing the lint errors and warnings.

**Comment by techievivek** [comment]
@makkoncept I will make a utility function that will accept a message, function to be called if pressed yes and function to be called if pressed no.
In fact, I am planning to even make more generic by setting user-defined value for buttons in the popup.
So that it can be used everywhere as a popup.
So (message, yes_function(), no_function(), cancel_text, ok_text) these will be the field.

**Comment by makkoncept** [comment]
Sounds good. I have reviewed your PR again. Let me know if you have any queries.

 Also, let's have the conversation about the implementation on the PR.
