### ISSUE TITLE
Add checkbox option to toggle on/off confirmation popup before clearing search results.

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#159]
This is an extension of https://github.com/creativecommons/ccsearch-browser-extension/issues/157. 

The checkbox can be added under the "Other Settings" tab on the options page.  Make sure that by default this feature should be turned off.

**Comment by techievivek** [comment]
@makkoncept Can I work on this one now?

**Comment by makkoncept** [comment]
@techievivek Sure, go ahead!

**Comment by techievivek** [comment]
@makkoncept I have implemented the functionalities for settings, I just have to check everytime one clicks on clear button. So should I continue development in the same branch of the modal one as I will be requiring those features or I should create a new branch?

**Comment by makkoncept** [comment]
The changes have been merged into the master. So, you can pull those changes and then checkout a different branch for this issue's PR. A different branch would be a lot better.

**Comment by techievivek** [comment]
@makkoncept ok sure.
