### ISSUE TITLE
CC Search extension page on mozilla site says it's not a recommended extension.

### ISSUE THREAD

**Issue by techievivek** [creativecommons/ccsearch-browser-extension#160]
**Is your feature request related to a problem? Please describe.**
[CC search extension](https://addons.mozilla.org/en-US/firefox/addon/cc-search-extension/) page on Mozilla says it's not a recommended extension.
![not-recommended-firefox](https://user-images.githubusercontent.com/35863227/75263635-45b06600-5814-11ea-892c-5b77fa9401cd.png)

**Describe the solution you'd like**
There are 2-ways to get through this.
1. We can request users to email amo-featured [at] mozilla [dot] org with a link to its AMO listing page. 
2. All extension must follow some **[best security practices](https://extensionworkshop.com/documentation/develop/build-a-secure-extension/)** , so we can work to improve on this.

**Describe alternatives you've considered**
To go with present scenario.

**Additional context**
If an extension is tagged `not recommended` by Mozilla then it will not be promoted or featured by Mozilla other than on the extension's original page. So if we work on this we can improve the visibility.

**Comment by makkoncept** [comment]
From the discussion on Slack:
> A large number of extensions on the firefox addon store has this warning. In fact, very few addons have the "recommended" badge and are featured on the Firefox addons front page. The good thing about cc search extension is that it does not have any serious permissions in manifest or content scripts (i.e scripts that can be injected into the pages that users visit), therefore when it is installed the user is not shown warnings like "this extension requires your permission to access your data for all websites, read and modify privacy settings)...

**Comment by Blackcipher101** [comment]
The warning can make people doubt the credibility and make them vary of installing the extension making a dent in the impact
