### ISSUE TITLE
Modify and Improve the "Delete all" button functionality

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#161]
**Is your feature request related to a problem? Please describe.**

There is a button "Delete all" in the bookmark section which deletes all the bookmarks. 

The export bookmark feature has also been moved from the options page to the bookmarks section. So, now we have two more buttons (refer to the screenshot below). Users can manually select the bookmarks they want and then export them by clicking the "Export bookmarks" button. If they want to export all of them, they can click the "Select all" button to select all the images and then press the "Export Bookmarks" button.

![Screenshot from 2020-02-26 19-03-47](https://user-images.githubusercontent.com/34679965/75349614-20cafa00-58cb-11ea-8a70-43b90146b846.png)

It would be good if we could mix these two features: Users might not want to delete all the bookmarks all at once, therefore let them select the images they want to delete.

**Describe the solution you'd like**
Change the "Delete all" button to "Delete", i.e make it delete only those images that are checked by the user. If they click on the button without selecting any of the bookmarks, then show a snackbar warning "No bookmarks selected".

**Comment by harsh551** [comment]
Hey, can I work on this issue?

**Comment by makkoncept** [comment]
@harsh551 go ahead.
