### ISSUE TITLE
Host the readme images on imgur

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#162]
**Is your feature request related to a problem? Please describe.**
10 images(670 kb) were added to the repository in https://github.com/creativecommons/ccsearch-browser-extension/pull/156. Their size is more than that of `src/` directory (which also has the license and provider images).

**Describe the solution you'd like**
Upload the image to Imgur and edit the readme to update the images src. Make sure to link the right image in the right place.

**Comment by lakshaybits** [comment]
Hi @makkoncept , Can I work on this issue ?

**Comment by makkoncept** [comment]
@lakshaybits go ahead.

**Comment by preetmishra** [comment]
@lakshaybits Hey, are you still working on this?

**Comment by lakshaybits** [comment]
@preetmishra  Yes, actually i have exams going on, so i was not able to give much time. I will complete it in a day or two.

**Comment by preetmishra** [comment]
@lakshaybits Alright.
