### ISSUE TITLE
API v1: Most image results are not rendering

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#165]
**Describe the bug**
The image thumbnails of the search results are not rendering. This happens for nearly 95% of the images.

**To Reproduce**
1. Make sure that you have pulled the latest changes
2. Search for anything
3. See error

**Expected behavior**
The thumbnails should render.

**Screenshots**

![Screenshot from 2020-02-27 22-31-07 (1)](https://user-images.githubusercontent.com/34679965/75473316-ee98c580-59ba-11ea-9a81-6d19e937bc4c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: Version 80.0.3987.106

**Comment by techievivek** [comment]
@makkoncept yes, I was receiving the same error, this is probably from end-point.

**Comment by techievivek** [comment]
@makkoncept Even without pulling the recent change, it is not rendering. And the error shows as 403 error.

**Comment by cristomathew** [comment]
> @makkoncept yes, I was receiving the same error, this is probably from end-point.

It seems to be an error from the client side, most probably the client does not have proper authorisation to access the content.
