### ISSUE TITLE
Clicking on icons is not always precise.

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#168]
**Describe the bug**
For example, sometimes when clicking on the filter icon, the search icon is clicked.

**Cause**
This is due to the very high padding on the individual icons. 
![Screenshot from 2020-03-02 08-53-31](https://user-images.githubusercontent.com/34679965/75643215-545baa80-5c64-11ea-8f8a-53617d77a7f9.png)

**Solution**
Decrease the padding, or remove it altogether. Then the readjustment and realignment of the icons need to be done.

**Comment by Maxslide** [comment]
Hey, i would be interested to solve this issue

**Comment by makkoncept** [comment]
@Maxslide go ahead

**Comment by Maxslide** [comment]
Hey, I have sent a pull request, kindly review it
