### ISSUE TITLE
API v1: Adopt the new error response schema

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#169]
**Is your feature request related to a problem? Please describe.**

The response schema of the API response in case of an error is better in version 1.0. For example, check out https://api.creativecommons.engineering/v1/images?q=+ and https://api.creativecommons.engineering/image/search?q=+

For every search, [checkValidationError](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/searchModule.js#L108) function checks for the error in the API response. It needs to be modified to work with the new version.

**Comment by Maxslide** [comment]
I would like to work on this issue

**Comment by makkoncept** [comment]
@Maxslide Let's work on a single issue at a time. I have reviewed your PR and changes are needed before we can merge it.

**Comment by cristomathew** [comment]
Hi Can I work on this

**Comment by makkoncept** [comment]
@cristomathew  You can work on 1 issue at a time. Your PR is still not merged. I have reviewed it. Post any queries that you may have on the PR.

**Comment by kss682** [comment]
Hi , Can I work on this issue.

**Comment by makkoncept** [comment]
@kss682 go ahead. Make sure to read [CONTRIBUTING.md](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/CONTRIBUTING.md).

**Comment by kss682** [comment]
@makkoncept So currently when an input error occurs  the response is "Not a valid search query" that should be made to "InputError".
