### ISSUE TITLE
Remove instances of "error-message" instances.

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#178]
The span with `error-message` in `popup.html` ([here](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/popup.html#L72)) is not being used in the extension. Remove instances of it (like the span, element selector, stylesheet rules, etc) from the code.

**Comment by cristomathew** [comment]
can i go ahead with it

**Comment by makkoncept** [comment]
@cristomathew Yeah, you can.
