### ISSUE TITLE
Add JSON parsing error handling

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#18]
**Descriptions**
When a user uploads a bookmarks JSON file, [this](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/options/options.js#L45) event listener parses the file.

An error occurs when an invalid JSON file is uploaded but no message or feedback is given to the user.

We need to add JSON parsing error handling and show an appropriate message like `Not valid json file` as a notification in the event listener.

**Comment by manisacharya** [comment]
Hello @makkoncept. I would like to work on this issue.
