### ISSUE TITLE
Deleted bookmarks are also exported (in the same user session)

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#182]
**Describe the bug**
In the same user session, the deleted bookmarks also make their way into the exported bookmarks. 
Follow the steps below to reproduce.

**To Reproduce**
1. Go to the bookmarks section (make sure to have at least1 bookmark).
2. Select some bookmarks (you can also click on "Select all")
3. Click on "Export bookmarks".
4. Now delete the selected bookmarks.
5. Again, click on "Export bookmarks".
6. On opening the file, you will see that the deleted bookmark ids.

**Expected behavior**
The deleted bookmarks should not be present in the exported bookmarks.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: Chrome v80.0.3987.122

**Comment by avivith** [comment]
Hi. Can I take this issue?

**Comment by makkoncept** [comment]
@avivith go ahead. Make sure to read the [CONTRIBUTING.md](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/CONTRIBUTING.md) and contributions and pr guidelines linked in there.

**Comment by avivith** [comment]
The problem was with the "delete (all)" button, which fix #180 solved.

**Comment by makkoncept** [comment]
@avivith I have also tested this and it seems to have been resolved. Thanks for pointing this out!
