### ISSUE TITLE
Inconsistent positioning of the image title 

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#223]
**Describe the bug**
The positioning of the image title for some source is perfect - 

eg: `Flickr` 

![Screenshot from 2020-04-17 18-20-30 (1)](https://user-images.githubusercontent.com/34679965/79571922-a9029a00-80d9-11ea-810c-cee3cac70903.png)

But for some sources, which have a thin icon, the title touches the bottom of the thumbnails and looks improper - see some examples below.

![Screenshot from 2020-04-17 18-21-17](https://user-images.githubusercontent.com/34679965/79571793-6a6cdf80-80d9-11ea-989d-10f64a3949c4.png)

![Screenshot from 2020-04-17 18-20-59](https://user-images.githubusercontent.com/34679965/79571827-7a84bf00-80d9-11ea-966f-4eb2d14427b7.png)

![Screenshot from 2020-04-17 18-19-32](https://user-images.githubusercontent.com/34679965/79571927-a99b3080-80d9-11ea-97d1-00c7365a721c.png)

**Expected behavior**
The positioning in the case of the `Flickr` source seems good.

To achieve that we can edit the thin icons to have a transparent border around them.

**Comment by rubenlorenzo** [comment]
Hello, can I work on solving it? My first option is increasing the margin-bottom to image-title.

**Comment by makkoncept** [comment]
Hi @rubenlorenzo. Sure, you can go ahead. I experimented a bit with this issue. Following are some thoughts:

- Increasing the margin-bottom of image-title is a good start but it will now work all the time. You see that the image title position depends on the size of the source icon. The source icons have different vertical sizes and therefore, a constant margin-bottom will not work for all.

- I tried adding a transparent border around the source icons in photoshop. This fixed the issue but the size of the rendered source icon became very small. You can improve upon that and experiment by only adding a transparent top/bottom border. This can be used to give a constant vertical size to all the icons and therefore the title position will be constant for all of them.

**Comment by rubenlorenzo** [comment]
I have changed only the border-bottom in image-title, because source-image depends on it. 
If I add it as a constant in both, source-image is higher. I have uploaded the change to my fork repository. So @makkoncept you could check it.

**Comment by makkoncept** [comment]
You can submit a PR and we can improve upon it. Also, go through the [PR guideline](https://opensource.creativecommons.org/contributing-code/pr-guidelines/) and [CONTRIBUTING.md](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/CONTRIBUTING.md) if you haven't already.

**Comment by makkoncept** [comment]
There is a better solution to this problem. It is basically motivated by how [search.creativecommons.org](http://search.creativecommons.org/) has re-implemented the way title of the image is shown. This will solve this problem and also the issue that sometimes the title is not visible when there is a light background in the current implementation.

![Screenshot from 2020-04-27 02-15-24](https://user-images.githubusercontent.com/34679965/80319217-fba42a80-882c-11ea-9697-c62d36238653.png)

The only downside to this is that the user has to click the thumbnail and open the information popup to see the source/provider of the image. A probable solution to this would be to display the source name on the cursor tooltip when the user hovers over the image title.

@rubenlorenzo What do you think?

**Comment by rubenlorenzo** [comment]
I think it's a good idea. The icon may apper with the others icons (license...) but situation on the right. The text frame with text, We can put less opacity.

**Comment by makkoncept** [comment]
@rubenlorenzo Adding source icon to the top right would make everything very clumsy as it also has a bookmarks icon and the selection checkbox(visible in bookmarks section). Anyways, changing the title to be displayed as described in the above comment is the new goal. If you want to continue working on this, let me know. You can also close the old PR.

**Comment by rubenlorenzo** [comment]
@makkoncept,  I can apply the last image. What do you think?

**Comment by makkoncept** [comment]
@rubenlorenzo what do you mean? 

The new goal is to implement the title to show like this. This should appear when we hover over the image.You can see this on http://search.creativecommons.org/
 ![](https://user-images.githubusercontent.com/34679965/80319217-fba42a80-882c-11ea-9697-c62d36238653.png)

**Comment by rubenlorenzo** [comment]
ok, I go to implement it.
