### ISSUE TITLE
Search results not persistent when user switches between bookmark and search section

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#224]
**Describe the bug**

We can easily imagine a user switching between the search and the bookmarks section in a single session. But during this switching, the search results are not persistent. This can become frustrating for regular users as they would have to search again and again or may have to adapt to not switch between the sections. Both of these alternatives do not promise a good User Experience.

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/34679965/79573596-858d1e80-80dc-11ea-9bd0-b875296418d9.gif)

Fixing this would also prevent some unnecessary requests to the API server.

**Additional context**
This happens when the option of storing search results across user sessions is toggled on. Therefore, this inconsistent behavior of the extension is another reason to fix this.

**To Reproduce**
Steps to reproduce the behavior (make sure to uncheck the :
1. Search for something 
2. Switch to the bookmarks section
3. Switch back to the search section.

**Comment by techievivek** [comment]
@makkoncept I tried to reproduce the error, but I am unable to achieve it. Could you please verify if I have followed it correctly, moreover I can't see the setting you talked about.
![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/35863227/79595409-6b633880-80fc-11ea-8f15-10b5026206f4.gif)

**Comment by makkoncept** [comment]
![Screenshot from 2020-04-17 22-52-35](https://user-images.githubusercontent.com/34679965/79596536-5edfdf80-80fe-11ea-8d54-20793439c03f.png)

I was talking about this setting. It is toggled on by default. You have to toggle it off to reproduce the bug.

**Comment by techievivek** [comment]
@makkoncept So this is more like when we are navigating back to home, it is thinking it as if we restarted the extension?

**Comment by makkoncept** [comment]
Yeah that's a high level way to describe this.

**Comment by techievivek** [comment]
@makkoncept I will like to work on this.

**Comment by makkoncept** [comment]
@techievivek Sure, go ahead.
