### ISSUE TITLE
Update footer text on landing page

### ISSUE THREAD

**Issue by kgodey** [creativecommons/ccsearch-browser-extension#229]
See corresponding Vocabulary ticket: https://github.com/creativecommons/vocabulary/issues/334

**Comment by makkoncept** [comment]
@kgodey I observed that the footer on https://search.creativecommons.org/ also have social media links but it's now showing [on the storybook](https://cc-vocabulary.netlify.app/?path=/story/patterns-footer--default-story). Maybe it's not updated?

**Comment by makkoncept** [comment]
I opened an issue https://github.com/creativecommons/vocabulary/issues/339.
