### ISSUE TITLE
Previous search filters show up in the drop down but are unchecked.

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#238]
**Describe the bug**
The search results and the associated filters and the title are stored in Local Storage and loaded up again in the next session. This feature is toggled on by default.  
The filters are correctly loaded and but you can see that they are not checked on in the dropdown.

**GIF**
![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/34679965/80542696-21673600-89cb-11ea-8da7-9d7a67fc90ed.gif)

**Expected behavior**
The applied filters must also be checked on in the dropdown.

**Comment by Arunhari333** [comment]
You are working on this issue, right?

**Comment by makkoncept** [comment]
Yes
