### ISSUE TITLE
Space under the footer when we search for something

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#25]
**Describe the bug**
After we search for something, as soon as the loader comes, there is some space below the footer which is removed when the image thumbnails are loaded.
See the screenshot below.

**To Reproduce**
1. Open the extension and search for anything
2. Observe the footer.

**Expected behavior**
Footer must not move up.

**Screenshots**
![Screenshot (202)_LI](https://user-images.githubusercontent.com/34679965/66055112-acc23b00-e552-11e9-823b-c35bb0dc2b2c.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 1.0.0

**Comment by zjael** [comment]
Will take a look. :)

**Comment by makkoncept** [comment]
Sure, go ahead!
