### ISSUE TITLE
Feature Request: Fixed header

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/ccsearch-browser-extension#277]
Thoughts on fixing the header to the top of the extension? It has a toolbar feel to me so could make sense.

**Comment by makkoncept** [comment]
Hi @zackkrida. Nice idea!  But the current design is going to change as we are integrating vocabulary and [this mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562).  In the mockup, you can see that some sections (which are also scrollable), the footer is fixed (eg: [Filter section](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=942%3A254) and [Bookmarks section](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=1089%3A4919)) so maybe a fixed header does not make much sense here. 

Tagging @panchovm for their opinion on this suggestion in the context of the new design.

**Comment by panchovm** [comment]
I like the suggestion, but maybe we can try the mockup and see how it feels the interaction and the daily use.

**Comment by makkoncept** [comment]
Okay. I'll come back to this after at least  major parts of the mock-up design are integrated in the extension.

**Comment by Aakash2408** [comment]
Hey @panchovm  Can you add images for reference of this issue?

**Comment by makkoncept** [comment]
Hi @Aakash2408, the images you are referring to is the new design of the extension ([Extension mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562)).

**Comment by Aakash2408** [comment]
> Hi @Aakash2408, the images you are referring to is the new design of the extension ([Extension mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562)).

ok so nothing in the development phase?

**Comment by makkoncept** [comment]
@Aakash2408 The integration of Mockup design and [CC Vocabulary](https://github.com/creativecommons/vocabulary) is underway. You can checkout [PR#276](https://github.com/creativecommons/ccsearch-browser-extension/pull/276). It's a WIP.

**Comment by makkoncept** [comment]
@zackkrida, @panchovm Please refer to the GIFs below to see how the fixed header looks in the new design. 


![new-extension-filters](https://user-images.githubusercontent.com/34679965/91367646-a43ab900-e824-11ea-9c65-e452c5198f59.gif)

![bookmarks-in-new-version](https://user-images.githubusercontent.com/34679965/91367638-a0a73200-e824-11ea-8f75-463ecba51e54.gif)

![source-section-light](https://user-images.githubusercontent.com/34679965/91367651-a56be600-e824-11ea-91ed-7e45adab96a2.gif)

I like it. What are your thought about this? Shall I go ahead and add this to the code?

**Comment by zackkrida** [comment]
I like it a lot let's confirm with @panchovm

**Comment by panchovm** [comment]
It will be also on the home page? for search results? what about the single result?

**Comment by makkoncept** [comment]
@panchovm The fixed header is also for the search result page but for the single result (image-detail section), in the place of the header we have the tabs and they are not fixed. The reasoning behind this was that I thought that unlike the search results or the bookmarks page, the height of the image detail section does not grow very much. The gifs are below for reference. I would like to know your thoughts and recommendations.

Search result

![search-results](https://user-images.githubusercontent.com/34679965/91455788-26b48e80-e8a0-11ea-96c2-f4ee5fbb6a93.gif)


single result (image - detail view)

![single-result](https://user-images.githubusercontent.com/34679965/91455307-89f1f100-e89f-11ea-9f96-09d460ca37b0.gif)

**Comment by panchovm** [comment]
I am not completely sure about this feature. The space for seeing results and browse them is reduced compared to CC search site. And with the header's height, is even less space.

I think it makes more sense to keep the search bar fixed, but I do understand that is a different feature.

I would like to hear other opinions as well (tagging @annatuma and @kgodey)

**Comment by makkoncept** [comment]
I think it's a valid point. Furthermore, I noticed that it will be a big concern on firefox because the extension popup there does not increase its height as you can see in the GIF below. So, I guess we can skip this. Anyways, thanks @zackkrida for the suggestion :100: 

![firefox](https://user-images.githubusercontent.com/34679965/91548685-61bbce00-e943-11ea-9236-bdd37af640a9.gif)
