### ISSUE TITLE
"Load more results" button appears below an empty search gallery

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#287]
**Describe the bug**
This bug is rather subtle. 
Toggling between the (empty) search section and the bookmarks section would not render the the "Load more results" button. 

![no error](https://user-images.githubusercontent.com/34679965/93981784-05ab6480-fd9e-11ea-9854-988cba0a813f.gif)

This button would appear if you open image-detail of any image while in the bookmarks section, and then toggle back to the search section. Also, clicking the button makes a render request with an empty search query (https://api.creativecommons.engineering/v1/images?q=&page=1&page_size=20&license=&source=&extension=&categories=&size=&aspect_ratio=&mature=false)

![error](https://user-images.githubusercontent.com/34679965/93981048-0d1e3e00-fd9d-11ea-85d0-bd8c77d5fa64.gif)

**Expected behavior**
The button should not appear in the second case.

**Comment by vivek32ta** [comment]
Hi @makkoncept 

Is it okay if I take this up?

Best,
Vivek

**Comment by vivek32ta** [comment]
Hi @makkoncept 

I fixed the bug by changing 2 lines of code. But when I try running ES Lint, I get this.... 

`ESLint: 5.16.0.`
`No files matching the pattern "'./src/**/*.js'" were found.`
`Please check for typing mistakes in the pattern.`

And since this is a pre-commit command, I'm not able to commit my changes.
What do you think I should do? 

Thanks.

**Comment by makkoncept** [comment]
Hi @vivek32ta, I am not able to mimic the error on my machine. Can you provide the following information for better debugging? Before that, you can delete the `node_modules/` and reinstall the dependencies and check if the error persists.

1. Have you changed the project directory structure? Please paste the screenshot of the file structure of the project as shown in your editor.

2. On your terminal, explicitly run the command from the root of the project: `eslint './src/**/*.js/'`. Please paste the output.

3. What is your Operating system? Also, tell the node and the npm version.

**Comment by vivek32ta** [comment]
Hey @makkoncept,

I figured it out. I'm using windows so single quotes don't identify as strings in command prompt. So I changed the eslint command in package.json with double quotes to....

`eslint \"./src/**/*.js\" \"./tests/**/*.js\"`

ES Lint works fine now.
