### ISSUE TITLE
Remove redundant license logos from the repository

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#288]
**Describe the bug**

The images and SVGs present in `src/popup/img/` (except _search.svg_) are no longer required in the project because:
- The license logos were used in the custom image component, which is now replaced by the vocabulary component.
- `cc-logo_white.png` and `ccheart_red.svg` are not being used in the new design.

Along with these images, their reference in the [webpack config](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/webpack.config.js#L67-L76) should also be removed.

**Comment by rajatdiptabiswas** [comment]
Hi @makkoncept 

I'd like to work on this. I'll try my best to get the issue fixed as soon as possible.

**Comment by makkoncept** [comment]
@rajatdiptabiswas Take your time. There's no hurry on this one.
