### ISSUE TITLE
Add license explanation tool tip in the filter section

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#292]
The users can click the question mark icons in the filter section on [CC Search](https://search.creativecommons.org/search?q=mountain) to see a brief explainer of each license. 

![Screenshot from 2020-10-01 22-42-25](https://user-images.githubusercontent.com/34679965/94842120-9f2ae400-0438-11eb-9af6-db33f101bcc7.png)

The same is to be implemented in the filters section of the extension. 

- The icons are already available in the [vocabulary](https://cc-vocabulary.netlify.app/?path=/docs/tokens-icons--figma)
- The design and the content will be identical to the CC Search implementation.

**Comment by sravan7** [comment]
@makkoncept 
I would like to work on it. please assign i to me

**Comment by abhinavjonnada82** [comment]
Can I get this with some instructions, please?

**Comment by makkoncept** [comment]
Sure! @abhinavjonnada82. 

As far as setting up the project for development is concerned, you can go through [build instructions](https://github.com/creativecommons/ccsearch-browser-extension#installation-from-source) and [INSTRUCTIONS.md](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/INSTRUCTIONS.md).

This particular issue is concerned with the filter section of the extension popup. You will find all the things related to extension popup under `src/popup/`. The HTML file for the popup is `src/popup/popup.html`, where you can find the markup [for license filters](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/popup.html#L82). 

The project uses SASS(a popular CSS preprocessor). The stylesheet rules concerned with the filters section is in [_search.scss](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/sass/layout/_search.scss). Any event listener functions can be defined in [filterModule.js](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/filterModule.js), which can be imported in [popup.js](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/popup.js) and attached to DOM elements. Also, any new DOM selectors should be put in [elements object](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/base.js#L1) in _base.js_.

**Comment by abhinavjonnada82** [comment]
@makkoncept hey thanks for the instructions. I'll be on it ASAP!
Thanks

**Comment by abhinavjonnada82** [comment]
hey @makkoncept is there slack channel or some kind of community chat. Where I can ask some questions?

**Comment by makkoncept** [comment]
Yes, you can join the [creative commons slack](https://opensource.creativecommons.org/community/#slack). BTW, If the questions are regarding this issue, there is no harm in discussing it here!

**Comment by abhinavjonnada82** [comment]
Sure let's do it over here! So just to rephrase what is in the ticket. You basically need a question mark symbol by the licenses and grab essential information and display on the tooltip?
1q.) should this thing should be done on the filter section?
2q.) from where should the information (about licenses and stuff) be grabbed and displayed on the tooltip?
3q.) is there a sample I can refer to?
Lastly thanks for answering my questions!

**Comment by makkoncept** [comment]
1a.) Yes, in the filters section.
![Screenshot from 2020-10-04 11-55-09](https://user-images.githubusercontent.com/34679965/95008565-a02a6400-0638-11eb-94fa-ad5f95a9937e.png)

2a.) You don't need to fetch the information from anywhere. The license information and their icons are not dynamic and therefore there is no harm in hardcoding them.

3a.) Yes, as mentioned in the issue description, you can checkout the filters section of [CC Search](https://search.creativecommons.org) to get an idea what the end result should look like. The information about the license can be taken from here itself.
![Peek 2020-10-04 12-00](https://user-images.githubusercontent.com/34679965/95008625-3068a900-0639-11eb-946a-b2e1caf6ab3a.gif)

**Comment by abhinavjonnada82** [comment]
Hey @makkoncept I'm in between jobs and have to prioritize my time. For now, I'm gonna unassign form the PR.

GL

**Comment by patelaryan7751** [comment]
hey @makkoncept  can you assign me this issue i would like to work on this issue.

**Comment by makkoncept** [comment]
@patelaryan7751 go ahead.

**Comment by patelaryan7751** [comment]
hey @makkoncept  i have fixed the issue but i am facing difficulty with some errors .
![error](https://user-images.githubusercontent.com/59426397/97710179-6aff1d80-1ae1-11eb-885c-d8a627a7d694.png)
can u help me how to solve this errors. i really want to contribute but i am a beginner so i do not have a expertise in this and this is my first contribution to the organization.

**Comment by makkoncept** [comment]
The build failed because of the formatting errors. Please go through the [INSTRUCTIONS.md](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/INSTRUCTIONS.md). Also, you can run `npm run prettier:check` to see the formatting errors causing this.

**Comment by patelaryan7751** [comment]
hello @makkoncept i have fixed the issue #294 i have added the explanation to the license as mentioned by you.
you can find the pull request #304  here and a gif of the extension below
![extension](https://user-images.githubusercontent.com/59426397/98319625-2d315600-2007-11eb-8ccd-68c6f4f8434d.gif)
If there is any issue in my work do notify me i would work again on it.

**Comment by RinkiyaKeDad** [comment]
Hey @patelaryan7751 are you still working on this issue? If yes would you like some help? And if you aren't working on it then can I take it up @makkoncept?

**Comment by patelaryan7751** [comment]
@RinkiyaKeDad ya you can work on this i am aslo now little busy with my acads as far as @makkoncept  reviewed my prev pull request
https://github.com/creativecommons/ccsearch-browser-extension/pull/304
i think i have to make more changes. You can take my files build upon it or else you can start from beginning.

**Comment by makkoncept** [comment]
I am syncing up with the updates to the project now because last week has been very hectic for me due to college. @RinkiyaKeDad you can go ahead with this issue.

**Comment by kshitij86** [comment]
@kgodey  @makkoncept This issue is still open and has the work required label. What other work is required on this ?

**Comment by makkoncept** [comment]
@kshitij86 the issue is currently being taken up (#310 )

**Comment by kshitij86** [comment]
@makkoncept Can I also contribute to it somehow? I've tried using the extension and I think it's a great tool. There aren't many good open issues either. Can you help me out here?

**Comment by makkoncept** [comment]
@kshitij86 as far as this particular issue is concerned, it's in it's final stages (I am working on the final improvements and will be pushing them soon to #310 as we are planning to include this fix in the next update). 

You can of course try out the extension and open bug reports or feature requests. We can discuss their feasibility and you can work on them if you like.
