### ISSUE TITLE
Load more results button appears even when there are no more pictures to show

### ISSUE THREAD

**Issue by devangmukherjee** [creativecommons/ccsearch-browser-extension#295]
**Describe the bug**
If you search for an image, which has no more new results to show, the "load more results" button still appears on the bottom and clicking on it does not do anything.

**To Reproduce**
1. Go to 'CC browser extension and type out 'penguin' in the search box'
2. Click on 'Go to filters and select 'Rawpixel' '
3. Scroll down to 'Load more results button and click on it'
4. See error - when the button is clicked no new results are shown.

**Comment by devangmukherjee** [comment]
@makkoncept I would like to work on this.

**Comment by makkoncept** [comment]
@devangmukherjee I can think of the following approach:
- After pressing the "load more" button if there are no images, then a notification can be shown to the user. Also, the "load more" button rendered after that should not be clickable.

**Comment by makkoncept** [comment]
Hey @devangmukherjee , I looked into this and found a better way to implement this. It involves the [search](https://github.com/creativecommons/ccsearch-browser-extension/blob/2cd092fe60cd4290ff5bfdae0f6884c585d93b79/src/popup/localUtils.js#L223), [nextRequest](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/popup.js#L68) and the [checkResultLength](https://github.com/creativecommons/ccsearch-browser-extension/blob/2cd092fe60cd4290ff5bfdae0f6884c585d93b79/src/popup/helper.js#L70) function. You will observe that `checkResultLength` already has the logic that we need but it is only triggered in `search` and not in `nextRequest`. Can we do something about it? (Tip: keep the code [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself))
