### ISSUE TITLE
Minor spelling errors

### ISSUE THREAD

**Issue by Melonadev** [creativecommons/ccsearch-browser-extension#308]
When I open the extension and go into 'Bookmarks', it shows the option '[Export All Bookmkarks](https://github.com/creativecommons/ccsearch-browser-extension/blob/2cd092fe60cd4290ff5bfdae0f6884c585d93b79/src/popup/popup.html#L175)'. It should be spelt 'Export All Bookmarks'.

![image](https://user-images.githubusercontent.com/66422959/98444286-c49fc180-214b-11eb-8ea2-ae7060e5bd06.png)

**Comment by devangmukherjee** [comment]
@makkoncept I would like to work on this.

**Comment by Melonadev** [comment]
Also, another error. The message '**Fetched latest sources succcessfully**' that shows up a few seconds after clicking on the extension should be '**Fetched latest sources successfully**'.

![image](https://user-images.githubusercontent.com/66422959/98466974-cdf16280-220d-11eb-98d1-2896c147fae2.png)

**Comment by Melonadev** [comment]
@devangmukherjee Would you like to fix the other one I mentioned above?

**Comment by devangmukherjee** [comment]
@Melonadev yes, I will make this change.

**Comment by RinkiyaKeDad** [comment]
Hey @Melonadev! Is this issue still assigned or can I work on it? Thanks.

**Comment by Melonadev** [comment]
@RinkiyaKeDad For some reason, the second issue I mentioned is not fixed yet. @devangmukherjee

**Comment by RinkiyaKeDad** [comment]
I saw the PR @Melonadev, doesn't the [recent commit](https://github.com/creativecommons/ccsearch-browser-extension/pull/309/files) fix the spellings of successfully?

**Comment by devangmukherjee** [comment]
@Melonadev I fixed the succesfully spelling in the same bookmarks PR.

**Comment by Melonadev** [comment]
@devangmukherjee That's good. Maybe your correction didn't reach the Chrome Web Store version.

**Comment by makkoncept** [comment]
Hey, Sorry I am caught up in some work and will address the issues and PRs as soon as I get the time. The changes will be reflected in the Chrome Web Store after the new build is pushed there.
