### ISSUE TITLE
Space under footer in bookmarks section

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#31]
**Describe the bug**
There is a space under footer in the bookmarks section when there are not enough images. As we keep adding the images, it is pushed down to its position.
Check the screenshot below.

**To Reproduce**
1. Open the extension.
2. Click on the bookmarks icon in the header to switch to the bookmarks section.
3. Remove all the bookmark images(if present).

**Expected behavior**
The footer must not move from its place.

**Screenshots**
![Screenshot (206)](https://user-images.githubusercontent.com/34679965/66336818-7d00a200-e95b-11e9-8123-dae269f04374.png)

**Desktop:**
 - OS: Windows
 - Browser: chrome

**Comment by imbipulkumar** [comment]
Hey @makkoncept 
Assign this issue to me.
Thank you!

**Comment by makkoncept** [comment]
Sure, Go ahead!

**Comment by ashishdutta007** [comment]
@makkoncept #33 is a duplicate issue created for this same issue.
You can find the PR for both of these in 
https://github.com/creativecommons/ccsearch-browser-extension/pull/34

**Comment by makkoncept** [comment]
@imbipulkumar This issue has been solved in #34. Sorry for the confusion. You can checkout other issues to work on or watch the repo for new ones.
Thanks
