### ISSUE TITLE
Clicking the bookmark in edit mode opens "image-detail" section instead of "selecting" it

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#311]
**Describe the bug**
In the "edit-mode", the click on a bookmark thumbnail is supposed to "select" it. But, now it opens the image-detail section. 

Refer to the GIFs below:

**Expected Behaviour**

![Peek 2020-11-25 16-48](https://user-images.githubusercontent.com/34679965/100221104-3b0b3480-2f3e-11eb-9de9-9885f10fc4f9.gif)

**Current Behaviour**

![Peek 2020-11-25 16-49](https://user-images.githubusercontent.com/34679965/100221095-39da0780-2f3e-11eb-98a4-5fd3ce82fec3.gif)

**To Reproduce**
1. Go to "bookmarks section".
2. Click on "Edit" link to enable "edit-mode".
3. Click on any bookmark thumbnail.

** Cause of this bug **
The cause is the [toggleEditView function](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/localUtils.js#L71). There, the `images` holds an `HTMLCollection` and `forEach` does not work on it. This can be easily fixed by using a `for..of` loop here. This bug is not in production. It sneaked in during the recent refactoring.

**Comment by RinkiyaKeDad** [comment]
Hey @makkoncept! I'd like to work on this issue.
