### ISSUE TITLE
Add setting to make the Navbar in the popup stick to the top

### ISSUE THREAD

**Issue by kshitij86** [creativecommons/ccsearch-browser-extension#314]
**Is your feature request related to a problem? Please describe.**
When scrolling through large lists, the navbar on the top is not accessible as it is fixed to the top. 

**Describe the solution you'd like**
The user interface can be improved a lot if the settings have an option to keep the navbar fixed to the top for easy access at all times.

**Describe alternatives you've considered**
Scrolling to the top always works I guess, but having the top bar fixed to easily switch between bookmarks, sources, settings seems like a good thing to have.

**Additional context**
I would be willing to work on this if this change gets approved.

**Comment by kshitij86** [comment]
@kgodey @makkoncept What do you think about this feature request?

**Comment by makkoncept** [comment]
Hey @kshitij86, This has already been discussed in https://github.com/creativecommons/ccsearch-browser-extension/issues/277 and we decided to not include this in the extension. You can refer to the conversation there for more info.
