### ISSUE TITLE
Formatting HTML Attribution on downloading text file

### ISSUE THREAD

**Issue by darkshredder** [creativecommons/ccsearch-browser-extension#316]
**Is your feature request related to a problem? Please describe.**
Currently on downloading Image and Attribution the HTML Attribution is not formatted and thus unreadable

**Describe the solution you'd like**
I would like to implement a function which gives out formatted output of HTML Attribution

**Additional context**

![Screenshot from 2020-12-13 00-57-18](https://user-images.githubusercontent.com/52625656/101993132-2cfb3900-3cde-11eb-9c02-205db6a2e7f1.png)
I have tried this function

![Screenshot from 2020-12-13 00-53-59](https://user-images.githubusercontent.com/52625656/101993136-397f9180-3cde-11eb-9c26-4380619c4ee8.png)
It gives the following output.

If this is approved I would like to implement this feature

**Comment by makkoncept** [comment]
@darkshredder Thanks for opening this issue. Please go ahead!
