### ISSUE TITLE
Bookmark icons not showing on hovering over the thumbnails

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#32]
**Describe the bug**
When we hover over the image, the bookmark icons are not showing. In place of it, `bookmark_border` and `bookmark` text is displayed.

This bug is a result of Pull https://github.com/creativecommons/ccsearch-browser-extension/pull/29 . We have moved from material icons to font awesome icons. The syntax of describing the icon is different in both of them.

_Material icons_: 
`<i class="material-icons" id="bookmark">bookmarks</i>`

_Font Awesome icon_:
`<i class="fa fa-bookmark" id="bookmark"></i>`

This bug is a result of this difference.

The code in question can be found [here](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/searchModule.js#L181)  and [here](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/bookmarkModule.js#L173)

**To Reproduce**
1. Open the extension and search for something.
2. Hover over the thumbnail.
3. Also, bookmark some image and hover over them in the bookmarks section.

**Expected behavior**
We should see the bookmark [this](https://fontawesome.com/v4.7.0/icon/bookmark-o) icon instead of text `bookmark_border` and [this](https://fontawesome.com/v4.7.0/icon/bookmark) icon instead of `bookmark` text on hovering over the images.

Also, the size and the position of the icons should also be adjusted if needed.

**Screenshots**
<br>

_Current_

![Screenshot (207)](https://user-images.githubusercontent.com/34679965/66337093-1760e580-e95c-11e9-87ab-7487b0bb0e3d.png)

<br>

_Target_

![search-images-attribution (1)](https://user-images.githubusercontent.com/34679965/66337785-71ae7600-e95d-11e9-8691-fb35d869299c.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Comment by bennetthanna** [comment]
Hi! I would be interested in fixing this issue if no one else has claimed it

**Comment by makkoncept** [comment]
Sure, Go ahead!

**Comment by Lawrence4code** [comment]
I'd like to work on this, please.

**Comment by makkoncept** [comment]
@Lawrence4code Thanks for your interest, but @bennetthanna is working on the issue right now. I will let you know if we need any help with this issue in the future. 
Thanks
