### ISSUE TITLE
Bookmark page's footer is out of place

### ISSUE THREAD

**Issue by codingonHP** [creativecommons/ccsearch-browser-extension#33]
### Issue
Footer on the Bookmarks page is out of place

![image](https://user-images.githubusercontent.com/7105293/66413851-da592980-ea15-11e9-8388-525044a659e6.png)

### Solution
CSS needs work

**Comment by ashishdutta007** [comment]
Will fix this

**Comment by makkoncept** [comment]
closing as it's a duplicate of #31.
