### ISSUE TITLE
Change Popup button styles (integrate CC-vocabulary)

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#36]
Change the style of the buttons in the information-popup( popup which opens when you click on image thumbnail) of the extension and replace it with cc-vocabulary styles.

**How to do it**
_Note_ - CC-vocabulary is already linked into the project, therefore you just need to add the appropriate classes and mimic the markup(if different) to change the styles.

Head over to the Buttons section in [CC-Vocabulary docs](https://opensource.creativecommons.org/cc-vocabulary/styleguide/#/Elements/Button).  Inspect the button element in dev-tools and copy its classes.  Adding the same classes (after removing unnecessary current ones) to the button element in the extension will change the styles.

For eg - [This button syntax](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/popup.html#L124) should change as follows:
Before:
```
<button class="btn-popup btn-download margin-right-small" id="download-image">Download Image</button>
```
After:
```
<button class="vocab button blue-colored normal-sized margin-right-small" id="download-image">
 <div class="content">
       Download Image
</div>
</button>
```
You should only change the styles of the Attribution tab. See the screenshot below.

**Screenshot**

_Before_
![Screenshot from 2019-11-05 00-21-30](https://user-images.githubusercontent.com/34679965/68151589-03fb6700-ff68-11e9-88fa-5acbfe4e142d.png)
_After_
![Screenshot from 2019-11-05 01-00-41](https://user-images.githubusercontent.com/34679965/68151603-08c01b00-ff68-11e9-9b8f-e6dffcd4f359.png)

**NOTE:** Focus only on the visual styles in this issue. If some functionality breaks, it will be resolved in other issues (example: copy to clipboard functionality is bound to break)

**Comment by ritesh-pandey** [comment]
@makkoncept I raised a PR for the issue. But it wasn't assigned to me. Sorry for that. I will follow the contribution guideline in future.

**Comment by makkoncept** [comment]
@ritesh-pandey, No problem! Go ahead and let me know if you run into some issues.
