### ISSUE TITLE
Add CC vocabulary paragraph styles to main extension popup

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#38]
There is some initial information when the extension opens. Add CC vocabulary styles to it.

**How to do it**
Note - CC-vocabulary is already linked into the project, therefore you just need to add the appropriate classes and mimic the markup(if different) to change the styles.

Head over to the [Paragraph section](https://opensource.creativecommons.org/cc-vocabulary/styleguide/#/Elements/Paragraph) in CC-Vocabulary docs. Inspect the paragraph element darker shaded blue color in dev-tools and copy its classes.
 
Use the copied classes on the [paragraph element](https://opensource.creativecommons.org/cc-vocabulary/styleguide/#/Elements/Paragraph) of the extension popup. Note that the current classes in the element are of use, therefore wrap the paragraph in a div tag with those classes.

**Comment by sharmaaditya570191** [comment]
Hi @makkoncept . Please have a look at my PR.
