### ISSUE TITLE
Add CC vocabulary paragraph and heading styles to bookmarks section

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#39]
Add appropriate classes of cc-vocabulary to heading and paragraph of the bookmarks section and also remove unnecessary style definitions from corresponding SCSS files.

**How to do it**
Note - [CC-vocabulary]() is already linked into the project, therefore you just need to add the appropriate classes(which you can see after inspecting the element in dev tools) and mimic the markup(if different) to change the styles.

**Paragraph**
- [Code in question](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/popup.html#L89)
- "No bookmarks yet" message is a negative indication, therefore use the corresponding classes from the [Paragraph section](https://opensource.creativecommons.org/cc-vocabulary/styleguide/#/Elements/Paragraph) of cc vocabulary docs.
- The current classes present in the element are necessary, so wrap the paragraph in a div with those classes.

**Heading**
- [Code in question](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/popup.html#L77)
- Add the classes and use h3 instead of h2.
- Remove the unnecessary styles from __bookmarks.scss_.
- To align the heading, wrap the heading in a div with class `text-align-center`

**Comment by sharmaaditya570191** [comment]
Hey @makkoncept . Please have a look at my PR and suggest changes if any.
