### ISSUE TITLE
Integrate CC-Vocabulary in text element in options page

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#40]
CC-vocabulary is integrated into other elements like checkboxes, tabs, buttons. We need to add it to text elements like paragraphs and headings too.

**How to do it**
Note - [CC-vocabulary](https://opensource.creativecommons.org/cc-vocabulary/styleguide/) is already linked into the project, therefore you just need to add the appropriate classes(which you can see after inspecting the element in dev tools) and mimic the markup(if different) to change the styles.

In this issue, the following elements must be targetted:
- The heading and the Note in the _Filters_ tab.
- The Note in the _Bookmarks_ tab.
- Heading in the _Dark-Mode_ tab.
- Heading and paragraph in _About_ tab.

Make sure to change the heading tags to adjust the size of headings.

## Reference
- [Paragraph section of CC-vocab styleguide](https://opensource.creativecommons.org/cc-vocabulary/styleguide/#/Elements/Paragraph)
- [Heading section of CC-vocab styleguide](https://opensource.creativecommons.org/cc-vocabulary/styleguide/#/Elements/Heading)

**Comment by sharmaaditya570191** [comment]
I would like to take this up @makkoncept .
