### ISSUE TITLE
Save the filters automatically without needing to press the save button

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#41]
Right now, on the options page of the extension, to save the filters to the localStorage, the user have to press the save button. There is also a note present, reminding the user to press the save button for the changes to take effect. 

We can improve on this by automatically triggering the save whenever the user selects (or deselect) some checkboxes. We should wait for a second before triggering the save though, as the user might be selecting and deselecting multiple options at once and showing the notification of save again and again is not what we want.

This is to be done in the filters tab only.

The driver code is in [options.js](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/options/options.js) and the [helpers.js](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/options/helper.js) contain the logic of saving the filters to localStorage.

Also, make sure to remove the Save button and Note from the filters tab.

**Comment by thegitone23** [comment]
I would like to work on this issue.
