### ISSUE TITLE
CC-0 license icon is not rendering in bookmarks section

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#42]
**Describe the bug**
When we hover over the image having a CC-0 license, it's icon is not present at the top. See the screenshots below.

This is not the case with all the CC-0 licensed images, but nonetheless, it should be fixed.

**To Reproduce**
1. Search for images while applying the CC-0 filter
2. Bookmark a few of them.
3. Hover over them in the bookmarks section.

**Expected behavior**
The Icon should be visible

**Screenshots**

_Search Section_
![Screenshot from 2019-11-07 00-13-51](https://user-images.githubusercontent.com/34679965/68334969-971bd480-0101-11ea-99b4-d94e46032927.png)

_Bookmarks Section_
![Screenshot from 2019-11-07 00-14-01](https://user-images.githubusercontent.com/34679965/68334970-97b46b00-0101-11ea-8d8c-49bede06c010.png)

**Desktop (please complete the following information):**
 - OS:  Linux
 - Browser: chrome
 - Version: 1.1.0

**Additional context**
_Reason_
In the bookmarks section, call to the `/image/{identifier}` endpoint of the Catalog API is made, where for some cc-0 licensed images, the license field value is written in uppercase which does not match with the license image names that the extension refers.
_Fix_
The obvious solution is to convert the license names to lower cases before dynamically embedding them to the src of img tag.

[Code in question](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/bookmarkModule.js#L158)

**Comment by ritesh-pandey** [comment]
I am unable to replicate the issue.

![Screenshot from 2019-11-28 14-21-06](https://user-images.githubusercontent.com/1433681/69791446-918a4980-11ea-11ea-983e-1256ff58803c.png)

**Comment by makkoncept** [comment]
@ritesh-pandey this bug was due to inconsistent casing. The license image names are in lowercase and for some images, the catalog api was sending the cc-0 license name in upper cases(`CC-0`). It is now fixed in the api ([see here](https://github.com/creativecommons/cccatalog-api/issues/382)).

But nonetheless, before using the license or provider names, we should first change them to lower cases. That's what this issue is now for.
