### ISSUE TITLE
Duplicate words in the about tab of the options page

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#60]
The word "CC Search" is present as a link and also a plain-text. Only the link is necessary.
Refer to the screenshot below.

![Screenshot from 2019-12-23 18-43-26](https://user-images.githubusercontent.com/34679965/71359999-580fe880-25b4-11ea-9401-009ba6f7cfd5.png)

**Comment by sharmaaditya570191** [comment]
I would like to take this up @makkoncept . Thanks.

**Comment by makkoncept** [comment]
solved in #61
