### ISSUE TITLE
Decrease spacing between search box and search results

### ISSUE THREAD

**Issue by sharmaaditya570191** [creativecommons/ccsearch-browser-extension#62]
**Describe the bug**
Currently there is extra space between the search box and the search results.

**To Reproduce**
1. Go to the extension
2. Search for something in the search box.
3. There is lot of space between search box and searh results.

**Expected behavior**
Space between search box and search results should be reduced.

**Screenshots**
![Screenshot from 2019-12-23 23-01-37](https://user-images.githubusercontent.com/42587159/71374128-88b94780-25df-11ea-9ae9-5048b2e5fd7d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 71.0

**Additional context**
I want to work on this.

**Comment by makkoncept** [comment]
Space is actually there for the filter section. Better implementation and UI is always better. Sure, go ahead!

**Comment by AmanR28** [comment]
Can I solve this issue now !!

**Comment by makkoncept** [comment]
Hi @AmanR28, thank you for showing interest in contributing to this project.
I would ask @sharmaaditya570191 to choose one of the issues that he wants to solve (maybe there is work in progress) and you can take the other one.
@sharmaaditya570191 please comment on the issue that you are working on currently.

**Comment by makkoncept** [comment]
Fixed in #75
