### ISSUE TITLE
Add popup on clicking Delete All button under Bookmarks

### ISSUE THREAD

**Issue by sharmaaditya570191** [creativecommons/ccsearch-browser-extension#63]
**Is your feature request related to a problem? Please describe.**
There is a fair probability that the user might click the `Delete All` button under `Bookmarks` mistakenly. 

**Describe the solution you'd like**
A alert popup box which takes confirmation from the user on clicking the `Delete All` button can solve the problem.

**Additional context**
I want to work on this. Updating with a PR soon.

**Comment by makkoncept** [comment]
It would be a nice feature! Sure, go ahead.

**Comment by AmanR28** [comment]
Can I implement this feature?

**Comment by sharmaaditya570191** [comment]
I will be sending a PR for this soon. Could you please have a look at #62 for now?

**Comment by AmanR28** [comment]
Ohk thanks @sharmaaditya570191

**Comment by sharmaaditya570191** [comment]
Can someone take this up please?

**Comment by Blackcipher101** [comment]
@sharmaaditya570191 @makkoncept Is it fine if it is a browser message

**Comment by makkoncept** [comment]
@Blackcipher101 No, because on some browsers the extension closes if a different popup opens anywhere else in the browser (eg: firefox).
You can go through the conversation in #82, I have written some implementation details there.

**Comment by makkoncept** [comment]
This issue has grown to be outdated and redundant as in issue #161 we are improving the workflow to delete the bookmarks.
