### ISSUE TITLE
Sharing on Twitter does not work

### ISSUE THREAD

**Issue by HeidiSeibold** [creativecommons/ccsearch-browser-extension#65]
**Describe the bug**
When I click the "share on twitter" button, it opens a new tab with twitter. That's all.

**To Reproduce**
1. Go to 'add-on'
1. Search for "baby cat"
2. Click on favorite baby cat image
2. Click on 'Share'
2. Click on twitter button

**Expected behavior**
A prephrased tweet with the image.

**Screenshots**
![image](https://user-images.githubusercontent.com/14146757/71907798-0dbe6800-316d-11ea-8670-46783a40aed0.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 71.0 (64-bit)

**Additional context**
The link that was shown in the new tab: https://twitter.com/home?status=I%20found%20an%20image%20through%20CC%20search%20%40creativecommons%3A%20https://www.flickr.com/photos/37040285@N02/5621276595

**Comment by makkoncept** [comment]
Thanks for reporting the issue @HeidiSeibold. It will be fixed soon.

**Comment by makkoncept** [comment]
@HeidiSeibold The issue has been fixed. The updated extension is pushed to the extension stores. While the change is live on Firefox and Opera, Chrome can take some days to review it.

**Comment by HeidiSeibold** [comment]
Wow, thanks. That was super fast! :tada: :sunflower:

**Comment by makkoncept** [comment]
@HeidiSeibold The update has been reviewed and accepted by the chrome store also. If your version has not been updated yet, you can manually update it by:
- navigating to `chrome://extensions`.
- toggling on `Developer mode`.
- clicking on _Update_ button
