### ISSUE TITLE
Firefox: Search window is only half shown if CC button is in overflow menu

### ISSUE THREAD

**Issue by swaldman3** [creativecommons/ccsearch-browser-extension#66]
If the CC Search button is moved to Firefox's "overflow menu" rather than kept visible on the toolbar, then when it is clicked only about half the window is visible, making the options / dark mode / etc buttons inaccessible. Screenshot attached.
![Untitled](https://user-images.githubusercontent.com/2036150/71966674-ed88ba80-31f9-11ea-9dcd-d668f444d883.png)

Tested in Firefox 68.3.0esr on Windows.

Steps to reproduce:
1. Install CC Search in Firefox
2. Right-click on toolbar, select "Customize", move the CC search button from the toolbar into the overflow menu. Leave Customize mode.
3. Open the overflow menu and click the CC Search item.

**Comment by makkoncept** [comment]
Hi, @swaldman3. Thanks for filling the issue.
You can read [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups#Popup_resizing) that the firefox addons, when moved to the overflow menu, are given a fixed width. The width is capped below the size of this extension ([here the person](https://discourse.mozilla.org/t/can-add-ons-webextensions-popups-determinate-whether-they-are-shown-in-the-overflow-menu-or-not/27937/9) says that it is 348px for windows and 425px for Linux(GNOME)). 
I have in https://github.com/creativecommons/ccsearch-browser-extension/commit/e5e201383861c8c88ae2c90446cc085e27002e76 made the extension to show a horizontal bar when there is a small width size (for ex: in overflow menu). The changes will be live in production in a couple of days. 
(Side Note: As this may not look good visually, you can consider moving it out of the overflow menu.
