### ISSUE TITLE
Big search query flows under the search and filter icons

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#7]
**Describe the bug**
A big search query in the input box shows under the icons.
Please refer to the screenshots below.

**Screenshots**
![Screenshot from 2019-06-25 18-48-24](https://user-images.githubusercontent.com/34679965/60101922-4622c980-977a-11e9-8a48-994268704f5f.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Comment by codingonHP** [comment]
**Proposal**
The font size of the query box is 130%. We can dynamically increase/decrease the font size based on the length of the query user types.

**Sample**
```js
let fontSize = Math.floor(130/fontSizeFactor);
```

**Comment by thegitone23** [comment]
May i try to solve this issue ??

**Comment by makkoncept** [comment]
I don't think that this is a good alternative as it seems hacky and will not be asthetically pleasing.

**Comment by thegitone23** [comment]
How about a ui change .. can we make the text field a little smaller than those buttons ?

**Comment by makkoncept** [comment]
The icons inside the input field look good and minimal.
I was thinking about something like in this [codepen](https://codepen.io/Mestika/pen/CiKlj)

**Comment by thegitone23** [comment]
> The icons inside the input field look good and minimal.
> I was thinking about something like in this [codepen](https://codepen.io/Mestika/pen/CiKlj)

Yeah this will work perfectly i guess .. may i attempt to go for this one ??

**Comment by codingonHP** [comment]
@makkoncept  I was thinking the same :)

**Comment by makkoncept** [comment]
@thegitone23 Go ahead!

**Comment by codingonHP** [comment]
@thegitone23 Nice work man!
I would still prefer that you remove the border around the text box and try to go for the horizontal scroll on text-overflow. The reason being that it is not aesthetically pleasing and kind breaks the flow. You are almost there. All you have to do is that break the search bar into text box and icons and then blend them together so that they look like one element but in reality its textbox + search area at exact same location without any internal borders separating them.
Hope it helps

**Comment by thegitone23** [comment]
> 
> 
> @thegitone23 Nice work man!
> I would still prefer that you remove the border around the text box and try to go for the horizontal scroll on text-overflow. The reason being that it is not aesthetically pleasing and kind breaks the flow. You are almost there. All you have to do is that break the search bar into text box and icons and then blend them together so that they look like one element but in reality its textbox + search area at exact same location without any internal borders separating them.
> Hope it helps

Thanks for the reply first of all, the text box and search area are i think already of the same width but that is the reason causing the overflow, i think javascript would be required to achieve the required effect, can you please suggest a way to do it without using javascript or otherwise should i add a new js file to do that for me, i am a little confused about where should i put the js to do stuff for me.

**Comment by codingonHP** [comment]
@thegitone23 
You don't need javascript for this. It can be done solely in CSS. I did quick CSS editing directly in chrome:

![image](https://user-images.githubusercontent.com/7105293/66282363-be9e3800-e8dc-11e9-8856-ea94bc9ae9a0.png)


This is just to give idea that only CSS is required

**Comment by thegitone23** [comment]
Thanks for the reply Sir, going straight to the issue the original effects can't be achieved as the serach area doesn't have the same focus properties as the input box, though I can set tabindex for search area but still the autofocus won't work for the search area and I don't think just using css I would be abel to apply borders and shadows to the search area when text area will have focus set to true. I hope I am not in the wrong direction here but I think the problem can simply be solved if I could set properties of search area when focus property of input box is set to true.

**Comment by makkoncept** [comment]
Hi @thegitone23, thanks for working on this. I am sorry, I didn't get the email notification of this and therefore was not able to take part in the discussion. 

Just like @codingonHP said, you are very close. I have checked your PR locally and can see that the problem is due to the focus animation present in the input field. I would suggest you remove the focus animation altogether from the input field. Just specify `outline: none` there so that the default blue highlight did not occur on focus. 

![Screenshot (205)](https://user-images.githubusercontent.com/34679965/66293265-e3f26c80-e903-11e9-8699-55ad2ad28893.png)

As far as giving the feedback to the user of the input field getting in focus is concerned, we can look for other ways to do it. After trying it myself, I even think that it might not even be necessary.

**Comment by thegitone23** [comment]
Thanks for the reply , I got your point, actually my initial solution was quite like the one you mentioned but the feedback issue was bothering me, anyways I will now work it out using your approach.

**Comment by thegitone23** [comment]
> Hi @thegitone23, thanks for working on this. I am sorry, I didn't get the email notification of this and therefore was not able to take part in the discussion.
> 
> Just like @codingonHP said, you are very close. I have checked your PR locally and can see that the problem is due to the focus animation present in the input field. I would suggest you remove the focus animation altogether from the input field. Just specify `outline: none` there so that the default blue highlight did not occur on focus.
> 
> ![Screenshot (205)](https://user-images.githubusercontent.com/34679965/66293265-e3f26c80-e903-11e9-8699-55ad2ad28893.png)
> 
> As far as giving the feedback to the user of the input field getting in focus is concerned, we can look for other ways to do it. After trying it myself, I even think that it might not even be necessary.

Thanks for the reply , I got your point, actually my initial solution was quite like the one you mentioned but the feedback issue was bothering me, anyways I will now work it out using your approach.

**Comment by thegitone23** [comment]
> Hi @thegitone23, thanks for working on this. I am sorry, I didn't get the email notification of this and therefore was not able to take part in the discussion.
> 
> Just like @codingonHP said, you are very close. I have checked your PR locally and can see that the problem is due to the focus animation present in the input field. I would suggest you remove the focus animation altogether from the input field. Just specify `outline: none` there so that the default blue highlight did not occur on focus.
> 
> ![Screenshot (205)](https://user-images.githubusercontent.com/34679965/66293265-e3f26c80-e903-11e9-8699-55ad2ad28893.png)
> 
> As far as giving the feedback to the user of the input field getting in focus is concerned, we can look for other ways to do it. After trying it myself, I even think that it might not even be necessary.

I have submitted the PR, i hope it does the job this time.
