### ISSUE TITLE
Improve UI of Filters 

### ISSUE THREAD

**Issue by AmanR28** [creativecommons/ccsearch-browser-extension#74]
UI of the filter form can be improved.
Here is a suggestion: 

![Screenshot from 2020-01-11 22-54-53](https://user-images.githubusercontent.com/54908728/72208403-2b226780-34c8-11ea-84e3-ba20b60d8275.png)

It also fixes #62 : Decrease spacing between search box and search results

PS: As it resolves issue #62, so, if granted permission, I want to work on it.

**Comment by sharmaaditya570191** [comment]
This is when the filter option is selected. I pointed to the space between search box and results when filter option is not selected. Could you please suggest or share screenshot when filter is not selected?

**Comment by AmanR28** [comment]
Yep, it fixes the space when filters are not selected.

![Screenshot from 2020-01-12 08-37-11](https://user-images.githubusercontent.com/54908728/72213583-55e7dc80-3517-11ea-81b9-c857e27a9da9.png)

**Comment by AmanR28** [comment]
So can I work on it?

**Comment by sharmaaditya570191** [comment]
Yes sure.
