### ISSUE TITLE
Fix search bar to top while scrolling.

### ISSUE THREAD

**Issue by nilshah98** [creativecommons/ccsearch-browser-extension#76]
**Is your feature request related to a problem? Please describe.**
Yes, when I am searching for images, as I scroll through the images below, the search bar and the filter options disappear.
So, if I want to change filter midway through browsing, or if I want to redefine the search query I have to scroll all the way through

**Describe the solution you'd like**
Stick only the navbar to the top when scrolling rather than sticking the bookmart and creative commons logo, as it will leave only little space to browse.
So, only stick the search bar, and with filter options.

**Describe alternatives you've considered**
None

**Additional context**
While scrolling -
![image](https://user-images.githubusercontent.com/22821480/72221553-10142e00-3582-11ea-93c0-e8238321dbf9.png)

**Preferred** -
sticking search bar to the top.

Also, additionally I would like to take up this issue.

**Comment by makkoncept** [comment]
Thanks, @nilshah98 for the feature suggestion. Sure, go ahead :+1:

**Comment by makkoncept** [comment]
Pursuing a better solution. More info in #78.
