### ISSUE TITLE
Add a "back to top" button

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#78]
**Is your feature request related to a problem? Please describe.**
This is with reference to #76. Though the problem is one that ought to be solved as it could become frustrating to scroll back to the top for every new query or changing the filters. But I think the solution can be better as far as UI and UX are concerned.
The problems with fixing the search bar to the top of the viewport are:
- It does not look good (especially in light mode) because of it's a huge size and the whitespace below the search bar.
- The whitespace will increase in the future as we add more filters.
- It is distracting and decreases the size of the viewport.

Using a "Back to top" button is a better option because:
- Its small size will not distract.
- Since searching for a new query or applying new filter options will essentially refill the grid and takes the users to the top one way or another, a fixed search bar is similar to this approach as far as the output is concerned.

**Describe the solution you'd like**
An absolute positioned button at the bottom right corner. It will appear only when we scroll down a bit after making a query. The user can click it to quickly reach the top.

A very good example is https://codepen.io/matthewcain/pen/ZepbeR

The design of it should resemble the UI of the extension.

**Comment by nilshah98** [comment]
I would like to work on this

**Comment by makkoncept** [comment]
Sure, go ahead. Also, close the PR #77

**Comment by nilshah98** [comment]
Done, thanks a lot.
