### ISSUE TITLE
Error while downloading images in absence of content script

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#8]
**Describe the bug**
The following error occurs when trying to download a photo from Behance provider:
`popup.html:1 Access to XMLHttpRequest at 'https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/180a6536683721.5725932eb3e24.jpg' from origin 'chrome-extension://obckdhkhgdbigeihagclikjmlioanfbb' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`
See the screenshot below.

This error is shown by some other providers also and at the same time images from some providers like Flickr, Thingiverse, Museums Victoria, etc does not give any error.

The error only occurs in chrome and opera browser while the download feature works as expected on firefox. The error goes when we set a `contents_scripts`  field in the manifest which targets at least all https web pages. I have used this as a temporary solution with an empty content script but the problem with this approach is that the extension is shown to have access to web pages and therefore a better solution is needed instead of the current hack.

**To Reproduce**
1. Build the extension
2. Remove the `content_scripts` field from chrome and opera `manifest.json`.
3. Search for any image from `Behance` provider.
4. Press the `download button`.

**Expected behavior**
The image should be downloaded without any error.

**Screenshots**
![Screenshot (22)](https://user-images.githubusercontent.com/34679965/63218403-b09f2700-c177-11e9-81f8-723e7ee8a312.png)

**Desktop (please complete the following informa.tion):**
 - OS: Windows (OS Build 17763.615)
 - Browser: Chrome [Version 76.0.3809.100 (64-bit)], Opera [Version : 62.0.3331.116]
 - Version [e.g. 1.0.0]

**Additional context**
The extension uses [download.js](http://danml.com/download.html)([npm](https://www.npmjs.com/package/download)) for downloading images.

The code which handles the downloading of image and attribution can be found in [infoPopupModule.js](https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/infoPopupModule.js)

**Comment by codingonHP** [comment]
@makkoncept I tried reproducing this issue in Chrome but couldn't. Can you check if you are still getting this error?

**Comment by makkoncept** [comment]
@codingonHP, I am also not getting the error. This is strange. I think we should not remove the `contents.js` file right now because this may be temporary. Waiting for more insight into this.

**Comment by makkoncept** [comment]
@codingonHP I am getting the error again. Actually, I didn't reload the extension after removing the `content_scripts` field from chrome `manifest.json`. We need to reload the extension in `chrome://extensions/` after we make the change in the manifest file.

**Comment by codingonHP** [comment]
created a PR for it :)
https://developer.chrome.com/extensions/xhr
