### ISSUE TITLE
Improve search functionality in the extension

### ISSUE THREAD

**Issue by sharmaaditya570191** [creativecommons/ccsearch-browser-extension#83]
**Description**  
Search functionality in the extension can be improved to listen to keyup events which can show search results as and when user types and can improve user experience. Currently the search results remain even if the user searches for something and then removes the searched text from the search box.

**Comment by sharmaaditya570191** [comment]
What are your views regarding this @makkoncept ? Thanks.

**Comment by makkoncept** [comment]
This is not possible (at least now)
- processing of the API result, generating individual image thumbnails and meta-data and filling them in masonry grid is a time-consuming process.
- Even if we bypass the above hurdle, this method would trigger a large number of API requests and the client is bound to pass the rate limit (60 request per minute).

**Comment by sharmaaditya570191** [comment]
Ok so instead of keyup events addition can we have onchange events to see if the search box is empty and if it is empty we can clear the search results?

**Comment by makkoncept** [comment]
I don't think that it's necessary. If the user is removing the string inside the search box to search for a new query, there is no need to clear the previous results as after a few moments they would press enter anyways. Also, I have not seen this kind of behavior in any contemporary applications (except the ones that show live results)
