### ISSUE TITLE
Add option to remove bookmark from main search result page

### ISSUE THREAD

**Issue by sharmaaditya570191** [creativecommons/ccsearch-browser-extension#84]
**Is your feature request related to a problem? Please describe.**
Currently an image is bookmarked from the search results if we click once on the bookmark icon and on clicking the bookmark icon it displays a message that image already bookmarked.

**Describe the solution you'd like**
Functionality of the bookmark icon button can be modified such that on 2nd click or even clicks it removes the bookmark and on 1st click or odd clicks it adds the image to the bookmark section.

![Screenshot from 2020-01-16 01-00-23](https://user-images.githubusercontent.com/42587159/72464089-a8b4e300-37fa-11ea-8348-6b36038b572d.png)

(The hovered button)

**Comment by sharmaaditya570191** [comment]
I would like to solve this.

**Comment by makkoncept** [comment]
@sharmaaditya570191 I have added my review on #82. Please solve that first.
Thanks

**Comment by DantrazTrev** [comment]
Hey , can I work on this ? Sorry I didn't knew the pattern for this repo ( There is already a PR)

**Comment by makkoncept** [comment]
Yeah, I will be testing your PR soon.
