### ISSUE TITLE
Initial content moves to the bottom when filters are opened

### ISSUE THREAD

**Issue by sharmaaditya570191** [creativecommons/ccsearch-browser-extension#85]
**Describe the bug**  
The home page text content is moved to the bottom of the extension when filter is selected.

**To Reproduce**
1. Go to home page of extension
2. Click on filter button
3. See error

**Expected behavior**
The text content should be properly aligned in the extension.

**Screenshots**
![Screenshot from 2020-01-16 01-03-45](https://user-images.githubusercontent.com/42587159/72464572-8a9bb280-37fb-11ea-8bda-dee8017e3d30.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 72.0.1

**Comment by sharmaaditya570191** [comment]
Can I take this up?

**Comment by makkoncept** [comment]
@sharmaaditya570191 I have added my review on #82. Please solve that first.
Thanks

**Comment by Dhruvi16** [comment]
I would like to take this up!
Thank you.

**Comment by makkoncept** [comment]
@Dhruvi16 sure, go ahead.

**Comment by makkoncept** [comment]
@Dhruvi16 can you please confirm if you are working on the issue?

**Comment by Dhruvi16** [comment]
YES! I will update you on this soon. Sorry for the delay.

**Comment by DantrazTrev** [comment]
Hey @Dhruvi16 are you still working on this issue?
