### ISSUE TITLE
Add a checkbox option to choose whether to persist the search results across sessions

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#86]
**Is your feature request related to a problem? Please describe.**
This is a complementary feature for #79. 
Some users may not want the extension to remember the last search and would want to start fresh every time they open the extension.

**Describe the solution you'd like**
A checkbox that the user can toggle on or off to enable/disable the feature. It would be present in a new options tab with title "Other Settings"

The template for this has been pushed in a532efe3a9016b962984c2b46e65a342fb836d7e.

**Comment by makkoncept** [comment]
As discussed in #79, @AmanR28 is working on this.

**Comment by AmanR28** [comment]
@makkoncept Thank you, sir.
As soon as PR #81 gets merged, I will create a pr for fixing this issue asap.

**Comment by Aman28temp** [comment]
Should I use cookie or local storage to store the setting for this.

**Comment by makkoncept** [comment]
Okay, I think it will take some time for me to review the PR. A lot is happening there.

**Comment by AmanR28** [comment]
Ohk will wait for it.

**Comment by AmanR28** [comment]
Can i work on some other issues till then, as both of my assigned issues are related to #81 to get merged.

**Comment by makkoncept** [comment]
Yes, comment on the unassigned issue you want to work on.

**Comment by DantrazTrev** [comment]
Can I work on this issue ?

**Comment by makkoncept** [comment]
@AmanR28 Are you working on this one?

**Comment by AmanR28** [comment]
@makkoncept This issue is a complementary feature for #79, on which i have a PR #109.

I will make a PR on this as soon as possible after issue #79 gets closed

**Comment by AmanR28** [comment]
@DantrazTrev  I am working on it.
