### ISSUE TITLE
RFE: better search queries

### ISSUE THREAD

**Issue by swaldman3** [creativecommons/ccsearch-browser-extension#87]
**Is your feature request related to a problem? Please describe.**
At the moment any search in CCSearch appears to be an "any words" search. If I enter "wind turbine seabed" I mostly get pictures of onshore wind turbines, or wind turbines built into buildings - not the desired subsea offshore images. 

**Describe the solution you'd like**
The ability to specify words that must be included in the results. e.g. if this were google I would do "wind turbine "seabed"". In some other places it might be "wind turbine +seabed".

**Describe alternatives you've considered**
A full boolean search system would be lovely, but isn't necessary here. I could also go back to searching on images.google.com with the right filters.

Thanks for considering!

**Comment by makkoncept** [comment]
Hi @swaldman3, thanks for the suggestion.
Actually, CC search does support search query enhancement to make the search more specific and meaningful to the user. For example: [mickey +mouse](https://search.creativecommons.org/search?li=&lt=&categories=&extension=&aspect_ratio=&size=&provider=&q=mickey%20%2Bmouse&searchBy=), [india +"taj mahal"](https://search.creativecommons.org/search?li=&lt=&categories=&extension=&aspect_ratio=&size=&provider=&q=india%20%2B%22taj%20mahal%22&searchBy=), [dogs huskies^4](https://search.creativecommons.org/search?li=&lt=&categories=&extension=&aspect_ratio=&size=&provider=&q=dogs%20huskies%5E4&searchBy=)(_boosting a term_), [title: "nature" AND provider: "met"](https://ccsearch.creativecommons.org/search?q=title%3A%20%22nature%22%20AND%20provider%3A%20%22met%22)

You can refer to the [CC Search Syntax Guide](https://search.creativecommons.org/search-help) or [Apache Lucene - Query Parser Syntax](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html)

As far as this project is concerned, the issue of special charachters in the search query (#88) has been solved in https://github.com/creativecommons/ccsearch-browser-extension/commit/b3caa7f5edcb0e8402591d956e2b774f4352b692 and https://github.com/creativecommons/ccsearch-browser-extension/commit/6ba08701ef6fc30f0a92874999f369875fdc44de. It will be in production in few days and then you can also do similar searches in the cc search extension itself. We will also add a search syntax guide in the options page with examples and use cases.

As you pointed out, the relevance of the images is also necessary to provide the best experience to the users. CC engineering team is working on it. I would defer the specifics to @aldenstpage and @kgodey. 
You can also read [Some thoughts on improving the relevance of images in CC Search](https://opensource.creativecommons.org/blog/entries/aws_grant/)

**Comment by swaldman3** [comment]
Fabulous, thanks - it sounds as though the problem at the moment is primarily a documentation one, that people just using the extension without knowing the infrastructure behind it don't know the syntax. Adding some info to the options page should help a lot.

**Comment by makkoncept** [comment]
@swaldman3 we have added CC search syntax guide in the options page which you can refer to for tips to make your queries more powerful. The update is live on all the browsers.
