### ISSUE TITLE
I cannot use spaces or special characters in search query

### ISSUE THREAD

**Issue by HeidiSeibold** [creativecommons/ccsearch-browser-extension#88]
**Describe the bug**
I cannot use spaces or special characters (e.g. `-`)

**To Reproduce**
1. Go to 'CC Search'
1. Enter 'CC-BY'
4. See error `no valid search query. Must be alphanumeric`

**Expected behavior**
I would like to see images with "CC-BY" as I do when I search on google
![image](https://user-images.githubusercontent.com/14146757/72541253-7b137c80-3882-11ea-9b45-fdc9071d226c.png)

**Desktop (please complete the following information):**
 - OS: Linux, Ubuntu
 - Browser Firefox
 - Version 72.0.1 (64-bit)

**Comment by AmanR28** [comment]
Yep, we should implement search that can handle search query with special characters.

**Comment by sharmaaditya570191** [comment]
Yes this can be a nice improvement.

**Comment by makkoncept** [comment]
@HeidiSeibold Thanks for reporting the issue!
This was done to fix issue #14. Back then the cc catalog API used to just give 500 error and not any useful feedback. That behavior has been fixed (https://github.com/creativecommons/cccatalog-api/pull/366) and therefore we can put that to use.

_Side note_: I have checked, and spaces in the search query are working.

**Comment by HeidiSeibold** [comment]
> Side note: I have checked, and spaces in the search query are working.

Ah I think I thought that it is not possible because I was searching for "Biergarten München" (beergarden munich), but there the "ü" was the problem.

Thanks for the search tool btw. I love it! :heart: :sunflower:

**Comment by makkoncept** [comment]
Oh, this is also an important observation because the regex pattern only had English ASCII characters specified.

> Thanks for the search tool btw. I love it!

Thanks, more exciting features coming very soon!

**Comment by makkoncept** [comment]
Issue has been fixed in b3caa7f and 6ba0870. The update has been pushed to the extension stores. Firefox has reviewed and accepted the changes. The updates will be up in the chrome and opera store in some days. This will be closed once the updates are live.

**Comment by makkoncept** [comment]
Opera has reviewed and accepted the update.

**Comment by makkoncept** [comment]
Chrome has also reviewed and accepted the update :100:
