### ISSUE TITLE
Add a privacy policy

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#9]
**Describe the solution you'd like**
It would be better to assure users that we don't collect any data from their computer. That only time connection to a remote server is made is when they search for images and when the extension update Provider lists.

**Describe alternatives you've considered**
Adding the privacy policy to the wiki would be a good option. We can add the link to the browser listing on various browser stores.

**Additional context**
We can also clarify that for syncing the data is shared with a remote server but the extension rather uses Firefox and Chrome built-in sync feature for it.

**Comment by kgodey** [comment]
tagging @sarahpearson

**Comment by makkoncept** [comment]
I have added a basic one in the [wiki](https://github.com/creativecommons/ccsearch-browser-extension/wiki/Privacy-Policy). It might need some work.

**Comment by kgodey** [comment]
Please don't link to it until @sarahpearson has had a chance to review it.

**Comment by makkoncept** [comment]
She can maybe edit and improve version in the wiki itself?

**Comment by kgodey** [comment]
Yes, that's fine but please don't link it publicly until she has.

**Comment by makkoncept** [comment]
Thanks @sarahpearson!
