### ISSUE TITLE
Add Option to Export Specific Bookmark, like exporting all bookmark

### ISSUE THREAD

**Issue by AmanR28** [creativecommons/ccsearch-browser-extension#90]
**Is your feature request related to a problem? Please describe.**
Many time users doesn't want to export all bookmark, allow them to export the specific bookmark them wants.

**Describe the solution you'd like**
Allow specific bookmarks to be exported.

This issue can be broken down into two tasks:
- [x] Implement Export Specific Functionality
- [x] Enhance UI of Export Specific 

**Additional context**
PS: I want to start working on Implementing Export Specific Functionality.

**Comment by makkoncept** [comment]
Nice idea! Can you please give more details about how you are planning to implement this? One thing not in favor of us is the small size of the extension. We don't want to clutter the UI.

**Comment by Aman28temp** [comment]
elements.exportSpecificBookmarksButton.addEventListener('click', () => {
        chrome.storage.sync.get({ bookmarks: [] }, (items) => {
          const bookmarksArray = items.bookmarks;

          bookmarksArray.forEach((bookmarkId) => {
            const url = 'http://api.creativecommons.engineering/image/${bookmarkId}';

            fetch(url)
              .then(data => data.json())
              .then((res) => {
                console.log(res);
                //
                //  Create DOM elements here
                //
                // elements.exportBookmark['0'].innerHTML += 
                //   <br />
                //   <div class="license filter-checkboxes">
                //     <input type="checkbox" class="vocab choice-field magenta-colored small-sized" id=${bookmarkId} />
                //     <label class="padding-left-smaller">${bookmarkId}</label>
                //     <img src = ${res.url} width= "300px" height = "300px" />
                //     <br />
                //   </div>;
              });
          });
        });
      });


This is a sample code, I am going to use.
I will not use any new dependency.

I will try to use functions that are already there, to ensure the size to be small.

**Comment by Aman28temp** [comment]
In Task for implementing this feature: 
  I will be using a normal table as UI, ensuring it matches the theme there.

For the task to implement UI for this feature, functions like "AddThumbnailToDOM" can be used to implement the consistent style for this feature.

**Comment by AmanR28** [comment]
elements.exportSpecificBookmarksButton.addEventListener('click', () => {
        chrome.storage.sync.get({ bookmarks: [] }, (items) => {
          const bookmarksArray = items.bookmarks;

          bookmarksArray.forEach((bookmarkId) => {
            const url = 'http://api.creativecommons.engineering/image/${bookmarkId}';

            fetch(url)
              .then(data => data.json())
              .then((res) => {
                console.log(res);
                //
                //  Create DOM elements here
                //
                // elements.exportBookmark['0'].innerHTML += 
                //   <br />
                //   <div class="license filter-checkboxes">
                //     <input type="checkbox" class="vocab choice-field magenta-colored small-sized" id=${bookmarkId} />
                //     <label class="padding-left-smaller">${bookmarkId}</label>
                //     <img src = ${res.url} width= "300px" height = "300px" />
                //     <br />
                //   </div>;
              });
          });
        });
      });


This is a sample code, I am going to use.
I will not use any new dependency.

I will try to use functions that are already there, to ensure the size to be small.

**Comment by AmanR28** [comment]
In Task for implementing this feature:
I will be using a normal table as UI, ensuring it matches the theme there.

For the task to implement UI for this feature, functions like "AddThumbnailToDOM" can be used to implement the consistent style for this feature.
