### ISSUE TITLE
No space between the images and the footer in bookmarks section

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/ccsearch-browser-extension#98]
**Describe the bug**
There is no space between the images at the bottom and the footer in the bookmarks section. When we hover over them, then the name and provider icon is also not visible. Please refer the screenshot below.

**To Reproduce**
1. Go to Extension
2. Search for something and bookmark images
3. Scroll to the bottom of the bookmarks section

**Expected behavior**
There should be some space between the footer and the images.

**Screenshots**
![Screenshot (239)](https://user-images.githubusercontent.com/34679965/73066820-17660080-3ecd-11ea-9943-88b0c699efbe.png)

**Comment by aryamanpuri** [comment]
@makkoncept Can I work on this?

**Comment by makkoncept** [comment]
@aryamanpuri yeah, go ahead

**Comment by makkoncept** [comment]
@aryamanpuri Did you figured out the solution of the problem you were facing yesterday(#104)? Can you please confirm that you are working on this issue ?

**Comment by aryamanpuri** [comment]
@makkoncept Yes it working now, and looking forward to solve the issue.

**Comment by aryamanpuri** [comment]
@makkoncept This problem is due to the fixed Footer so unless it is changed to the end of the page this problem will occur. What are your views on this?

**Comment by AmanR28** [comment]
@aryamanpuri Try giving some margin at bottom.

**Comment by makkoncept** [comment]
@aryamanpuri Make the PR with whatever best solution you can come up with, we can modify and polish it there only.

**Comment by makkoncept** [comment]
@aryamanpuri are you working on this? We have to fix this bug in the next release (which is scheduled on Monday)

**Comment by aryamanpuri** [comment]
@makkoncept I am not able to give time to this issue.
can you assign someone else?
